// vue/src/components/authors/AuthorList.vue
<template>
  <div class="app-col">
    <div class="title-row-wrapper">
      <div class="title-row">
        <div class="d-flex align-items-center">
          <h1>Authors</h1>
          <div class="input-group ms-2 ms-lg-5">
            <input @keyup="filter(filterInput)" v-model="filterInput" autofocus class="form-control" placeholder="filter"
                   aria-label="Filter">
            <span class="input-group-text">
              <font-awesome-icon icon="filter" size="lg"/>
            </span>
          </div>
        </div>
        <button @click="navigateToNewAuthor()" class="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">
          add Author
        </button>
      </div>
    </div>
    <div>
      <LoadingIndicatorOverlayWrapper :show-overlay="authorsLoading" spinner-size="5x">
        <div style="height: 300px">
          <AuthorTable @authorSelect="onAuthorSelected" :authors="filteredAuthors"></AuthorTable>
        </div>
      </LoadingIndicatorOverlayWrapper>
    </div>
  </div>

</template>

<script setup lang="ts">
import type {Author} from '../../../../react/src/mock-backend/author/Author';
import type {EnrichedAuthor} from '../../../../react/src/mock-backend/author/EnrichedAuthor';
import {findAllAuthors} from '../../../../react/src/mock-backend/author/author-mock-data';
import router from '@/router';
import {enrichWithCalculatedFields} from '../../../../react/src/mock-backend/author/author-util';
import AuthorTable from '@/components/authors/AuthorTable.vue';
import {onMounted, ref} from "vue";
import LoadingIndicatorOverlayWrapper from '@/components/shared/LoadingIndicatorOverlayWrapper.vue';

const loadedAuthors = ref<Author[]>([]);
const filteredAuthors = ref<Author[]>([]);
const authorsLoading = ref(true);

console.log("initializing AuthorList");

onMounted(() => {
  console.log(`onMounted`);
  loadAllAuthors();
})

const filterInput = ref("");
const loadAllAuthors = () => {
  findAllAuthors().subscribe({
    next: (authors: Author[]) => {
      console.log("findAll SUCCESS", authors);
      authors = authors.map(a => enrichWithCalculatedFields(a));
      loadedAuthors.value = [...authors];
      filteredAuthors.value = [...authors];
      authorsLoading.value = false
      console.log("findAll SUCCESS", loadedAuthors);
    }
  });
}

const filter = (term: string) => {
  console.log("filter", term);
  filteredAuthors.value = loadedAuthors.value?.filter(a =>
    (a.firstname + " " + a.lastname).toLocaleLowerCase().includes(term) ||
    (a.lastname + " " + a.firstname).toLocaleLowerCase().includes(term)
  );
}

const onAuthorSelected = (author: EnrichedAuthor) => {
  console.log("onAuthorSelected", author);
  router.push("/author/" + author.id);
}

const navigateToNewAuthor = () => {
  console.log("navigateToNewAuthor");
  router.push("/author/edit/new");
}

</script>

<style scoped>
</style>

// react/src/features/authors/author-list.tsx
import React, {SyntheticEvent, useEffect, useState} from 'react';
import AuthorTable from './author-table';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import {Paper} from '@mui/material';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faFilter} from '@fortawesome/free-solid-svg-icons';
import {useNavigate} from 'react-router-dom';
import {EnrichedAuthor} from '../../mock-backend/author/EnrichedAuthor';
import {enrichWithCalculatedFields} from '../../mock-backend/author/author-util';
import {Author} from '../../mock-backend/author/Author';
import {findAllAuthors} from '../../mock-backend/author/author-mock-data';

interface AuthorListState {
  authors: EnrichedAuthor[],
  filteredAuthors: EnrichedAuthor[],
  authorsLoading: boolean
}

const defaultState: AuthorListState = {
  authors: [],
  filteredAuthors: [],
  authorsLoading: true
}

const AuthorList = () => {

  const navigate = useNavigate();
  const [authorListState, setAuthorListState] = useState(defaultState);

  useEffect(() => loadAllAuthors(), []);

  function handleFilterKeyup(event: SyntheticEvent) {
    const searchTerm = (event.target as HTMLInputElement).value;

    setAuthorListState(prevState => {
      return {
        ...prevState, filteredAuthors: prevState.authors.filter(a =>
          (a.firstname + " " + a.lastname).toLocaleLowerCase().includes(searchTerm) ||
          (a.lastname + " " + a.firstname).toLocaleLowerCase().includes(searchTerm)
        )
      }
    })
  }

  function handleAuthorSelected(author: EnrichedAuthor) {
    navigate("" + author.id);
  }

  function navigateToNewAuthor() {
    navigate("edit/new");
  }

  function loadAllAuthors() {
    console.log("loadAllAuthors");
    setAuthorListState({authors: [], filteredAuthors: [], authorsLoading: true});

    findAllAuthors().subscribe(
      {
        next: (results: Author[]) => {
          console.log("findAllAuthors SUCCESS", results);
          const enrichedAuthors = results.map(a => enrichWithCalculatedFields(a));
          setAuthorListState({authors: enrichedAuthors, filteredAuthors: enrichedAuthors, authorsLoading: false});
        },
        error: (error: any) => {
          console.log("findAllAuthors ERROR", error);
        }
      });
  }

  return (
    <div className="comp-wrapper">
      <Paper elevation={8} className="app-col">
        <div className="title-row">
          <div className="d-flex align-items-center justify-content-between flex-wrap">
            <div className="d-flex align-items-center">
              <h1>Authors</h1>
              <div className="input-group ms-2 ms-lg-5">
                <input onKeyUp={(e) => handleFilterKeyup(e)} className="form-control" placeholder="filter" aria-label="Filter"/>
                <span className="input-group-text"><FontAwesomeIcon icon={faFilter} size={'lg'}/></span>
              </div>
            </div>
          </div>
          <button onClick={() => navigateToNewAuthor()} className="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">add Author</button>
        </div>
        <LoadingIndicatorWrapper loading={authorListState.authorsLoading}>
          <div className="pb-3">
            <AuthorTable authors={authorListState.filteredAuthors} authorSelected={(author => handleAuthorSelected(author))}/>
          </div>
        </LoadingIndicatorWrapper>
      </Paper>
    </div>
  );
};

export default AuthorList;
