// vue/src/components/authors/AuthorTable.vue
<template>
  <div class="table-wrapper">
    <q-table
      :rows="authors"
      :columns="columns"
      row-key="id"
      no-data-label="No authors found"
      @row-click="onRowClick"
    >
      <template v-slot:body-cell-penName="props">
        <q-td :props="props">
          <div v-if="props.row.penName" class="my-table-details">
            <font-awesome-icon icon="check" style="font-size: 1.5rem"/>
          </div>
        </q-td>
      </template>
      <template v-slot:body-cell-gender="props">
        <q-td :props="props" class="gender-col">
          <GenderIcon :gender="props.row.gender" show-label/>
        </q-td>
      </template>
      <template v-slot:bottom-row>
        <!-- intentionally empty-->
      </template>
      <template v-slot:bottom>
        <!-- intentionally empty-->
      </template>
      <template v-slot:no-data>
        <!-- intentionally empty-->
      </template>
    </q-table>
  </div>
</template>

<script setup lang="ts">
import type {EnrichedAuthor} from '../../../../react/src/mock-backend/author/EnrichedAuthor';
import type {DateTime} from 'luxon';
import GenderIcon from '@/components/shared/GenderIcon.vue';
import router from '@/router';

defineProps<{
  authors: EnrichedAuthor[]
}>()

function getDateOfDeathIfPresent(author: EnrichedAuthor): string {
  if (author?.dateOfDeath) {
    return author.dateOfDeath?.toFormat("dd.LL.yyyy") + " in " + author.placeOfBirth;
  } else {
    return "";
  }
}

function onRowClick(evt: PointerEvent, row: EnrichedAuthor) {
  console.log('clicked on', evt, row)
  router.push('/author/' + row.id);
}

const columns = [
  {
    name: 'firstname',
    label: 'FIRSTNAME',
    align: 'start',
    field: 'firstname',
    sortable: true
  },
  {name: 'lastname', align: 'start', label: 'LASTNAME', field: 'lastname', sortable: true},
  {name: 'gender', label: 'GENDER', field: 'gender', sortable: true},
  {name: 'penName', label: 'PEN NAME', field: 'penName', sortable: true},
  {
    name: 'birthdate', label: 'BIRTHDATE', sortable: true,
    field: (row: EnrichedAuthor) => row.birthdate?.toFormat("dd.LL.yyyy") + " in " + row.placeOfBirth,
    sort: (a: DateTime, b: DateTime, rowA: EnrichedAuthor, rowB: EnrichedAuthor) => dateCompare(rowA.birthdate, rowB.birthdate)
  },
  {name: 'age', label: 'AGE', sortable: true, field: (row: EnrichedAuthor) => row.age},
  {
    name: 'dateOfDeath',
    label: 'DATE OF DEATH',
    field: (row: EnrichedAuthor) => getDateOfDeathIfPresent(row),
    sortable: true,
    sort: (a: DateTime, b: DateTime, rowA: EnrichedAuthor, rowB: EnrichedAuthor) => dateCompare(rowA.dateOfDeath, rowB.dateOfDeath)
  },
]

function dateCompare(a: DateTime | undefined, b: DateTime | undefined) {
  console.log("dateCompare", a, b);
  if (!a) {
    return -1;
  }
  if (!b) {
    return 1;
  }
  return (a.toMillis() - b.toMillis());
}
</script>


<style scoped lang="scss">
.gender-col {
  display: flex;
  align-items: center;
}

</style>

// react/src/features/authors/author-table.tsx
import React, {memo} from 'react';
import {EnrichedAuthor} from '@local/mock-backend/author/EnrichedAuthor';
import {Box, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TableSortLabel} from '@mui/material';
import {faCheck} from '@fortawesome/free-solid-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import GenderDisplay from '../../shared/GenderDisplay';
import {useWindowSize} from '../../util/window-resize.hook';

interface AuthorTableProps {
  authors: EnrichedAuthor[];
  authorSelected: (author: EnrichedAuthor) => void;
}

const AuthorTable = (props: AuthorTableProps) => {
  const [order, setOrder] = React.useState<"asc" | "desc">('asc');
  const [orderBy, setOrderBy] = React.useState('lastname');
  const [width] = useWindowSize();

  console.log("AuthorTable", props);

  const createSortHandler = (property: string) => (event: any) => {
    handleRequestSort(event, property);
  };

  const handleRequestSort = (event: any, property: string) => {
    const isAsc = orderBy === property && order === 'asc';
    setOrder(isAsc ? 'desc' : 'asc');
    setOrderBy(property);
  };

  console.log("AuthorTable");
  const columns = [
    {field: 'firstname', headerName: 'FIRSTNAME', alwaysShow: true},
    {field: 'lastname', headerName: 'LASTNAME', alwaysShow: true},
    {field: 'gender', headerName: 'GENDER', alwaysShow: false},
    {field: 'penName', headerName: 'PEN NAME', alwaysShow: false},
    {field: 'birthdate', headerName: 'BIRTHDATE', alwaysShow: false},
    {field: 'age', headerName: 'AGE', alwaysShow: false},
    {field: 'dateOfDeath', headerName: 'DATE OF DEATH', alwaysShow: false}
  ];

  //TODO show spinner
  function descendingComparator(a: any, b: any, field: string) {
    if (!b[field] || b[field] < a[field]) {
      return -1;
    }
    if (!a[field] || b[field] > a[field]) {
      return 1;
    }
    return 0;
  }

  function getComparator(direction: string, field: string) {
    return direction === 'desc'
        ? (a: any, b: any) => descendingComparator(a, b, field)
        : (a: any, b: any) => -descendingComparator(a, b, field);
  }

  function handleRowSelected(author: EnrichedAuthor) {
    props.authorSelected(author);
  }

  return (
      <>
        <TableContainer component={Paper}>
          <Table size="small" aria-label="simple table">
            <TableHead>
              <TableRow>
                {columns.map(h =>
                    <TableCell key={h.field} sx={{display: ((!h.alwaysShow && width <= 800) ? "none" : "table-cell")}}>
                      <TableSortLabel active={orderBy === h.field} direction={order}
                                      onClick={createSortHandler(h.field)}>
                        <Box component="span" sx={{display: "box"}}>
                          {h.headerName}
                        </Box>
                      </TableSortLabel>
                    </TableCell>
                )}
              </TableRow>
            </TableHead>
            <TableBody>
              {props.authors.slice().sort(getComparator(order, orderBy)).map((a: EnrichedAuthor) => (
                  <TableRow
                      onClick={() => handleRowSelected(a)}
                      key={a.id}
                      sx={{'&:last-child td, &:last-child th': {border: 0}}}
                      className="selectable-table-row"
                  >
                    <TableCell component="th" scope="row">{a.firstname}</TableCell>
                    <TableCell component="th" scope="row">{a.lastname}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}><GenderDisplay
                        gender={a.gender}/></TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.penName ?
                        <FontAwesomeIcon icon={faCheck} size={'lg'}/> : ""}</TableCell>
                    <TableCell component="th" scope="row"
                               sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.birthdate?.toFormat("dd.LL.yyyy")} in {a.placeOfBirth}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.age}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>
                      {a.dateOfDeath ? (a.dateOfDeath?.toFormat("dd.LL.yyyy") + " in " + a.placeOfDeath) : ""}
                    </TableCell>
                  </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </>
  );
};

export default memo(AuthorTable);
