// angular/src/app/authors/author-edit/author-edit.component.ts
import {Component, OnInit} from '@angular/core';
import Author from '../../../../../mock-backend/author/Author';
import {findById} from '../../../../../mock-backend/author/AuthorMockService';
import {ActivatedRoute} from '@angular/router';
import {GlobalMessageService} from '../../core/global-message.service';
import {FormControl, FormGroup, Validators} from '@angular/forms';

@Component({
  selector: 'app-author-edit',
  templateUrl: './author-edit.component.html',
  styleUrls: ['./author-edit.component.scss']
})
export class AuthorEditComponent implements OnInit {
  author?: Author;

  formGroup = new FormGroup({
    id: new FormControl(null),
    firstname: new FormControl(null, Validators.required),
    lastname: new FormControl(null, Validators.required),
    gender: new FormControl(null, Validators.required),
    penName: new FormControl(null, Validators.required),
    birthdate: new FormControl(null, Validators.required),
    dateOfDeath: new FormControl(),
  });

  constructor(private activatedRoute: ActivatedRoute, private globalMessageService: GlobalMessageService) {
  }

  ngOnInit(): void {
    this.activatedRoute.params.subscribe(
        params => {
          const id = params['id'];
          if (id === "new") {
            //TODO create new author
            // author = new Author();

          }else{
            this.loadAuthor(Number(id));
          }
        }
    )

  }

  loadAuthor(id: number) {
    findById(id).subscribe({
      next: (author: Author) => {
        console.log("findById", author);
        this.author = author;
        this.formGroup.patchValue(author);
      },
      error: (error) => {
        this.globalMessageService.setAlertMessage("danger", "Unable to load Authors: ", error);
        console.log("error occured");
      }
    });
  }

}

<div class="app-col mat-elevation-z8">
  <div class="p-2 ms-lg-3">
    <div class="d-flex align-items-center justify-content-between flex-wrap" style="min-height: 48px;">
      <ng-container *ngIf="!isLoading">
        <h1 *ngIf="!formGroup.get('id')?.value">New Author</h1>
        <h1 *ngIf="!isLoading && formGroup.get('id')?.value">
          <span class="d-none d-lg-inline h1">Author </span>
          <span class="h1">{{fullname}}</span>
        </h1>
      </ng-container>
      <button *ngIf="formGroup.get('id')?.value" (confirm)="deleteAuthor()" class="btn btn-danger btn-lg me-2 me-lg-4"
              appConfirmation confirmTitle="Delete Author" confirmButtonText="delete" confirmButtonType="danger"
              confirmMessage="Are you sure that you want to delete <strong>{{fullname}}</strong>?<br />This action cannot be undone!"
      >delete
      </button>
    </div>
  </div>

  <div [formGroup]="formGroup" style="border-top: 2px solid gray;">
    <app-loading-indicator-overlay-wrapper [showOverlay]="isLoading" spinnerSize="6x">
      <div class="row mx-3 gx-0 gx-lg-5">
        <div class="col-lg-6 pt-2">
          <h2 class="mb-2">Personal Data</h2>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Firstname</mat-label>
            <input matInput placeholder="Firstname" formControlName="firstname" required>
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Lastname</mat-label>
            <input matInput placeholder="Lastname" formControlName="lastname" required>
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Birthdate</mat-label>
            <input matInput [matDatepicker]="birthdatePicker" formControlName="birthdate">
            <mat-datepicker-toggle matSuffix [for]="birthdatePicker"></mat-datepicker-toggle>
            <mat-datepicker #birthdatePicker></mat-datepicker>
            <mat-error>input required</mat-error>
          </mat-form-field>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Place of birth</mat-label>
            <input matInput placeholder="Place of birth" formControlName="placeOfBirth" required>
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Date of death</mat-label>
            <input matInput [matDatepicker]="dateOfDeathPicker" formControlName="dateOfDeath">
            <mat-datepicker-toggle matSuffix [for]="dateOfDeathPicker"></mat-datepicker-toggle>
            <mat-datepicker #dateOfDeathPicker></mat-datepicker>
            <mat-error>input required</mat-error>
          </mat-form-field>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Place of death</mat-label>
            <input matInput placeholder="Place of death" formControlName="placeOfDeath">
            <mat-error>input required</mat-error>
          </mat-form-field>

          <div class="row mb-4 align-items-center gender-input-row">
            <div class="col-auto">
              <span class="ms-2">Gender <span class="required-asterisk">*</span></span>
            </div>
            <div class="col-auto ps-2f">
              <mat-button-toggle-group formControlName="gender">
                <mat-button-toggle value="MALE" class="d-flex align-items-center justify-content-center">
                  <app-gender-icon gender="MALE" [showLabel]="true"></app-gender-icon>
                </mat-button-toggle>
                <mat-button-toggle value="FEMALE" class="d-flex align-items-center justify-content-center">
                  <app-gender-icon gender="FEMALE" [showLabel]="true"></app-gender-icon>
                </mat-button-toggle>
                <mat-button-toggle value="NON_BINARY" class="d-flex align-items-center justify-content-center">
                  <app-gender-icon gender="NON_BINARY" [showLabel]="true"></app-gender-icon>
                </mat-button-toggle>
              </mat-button-toggle-group>
            </div>
            <app-reactive-validation-display [control]="formGroup?.get('gender')" class="gender-error-label"></app-reactive-validation-display>
          </div>
          <div class="row mb-4 mb-lg-0 align-items-center">
            <div class="col-auto">
              <label for="penName" class="ms-2">Pen name</label>
            </div>
            <div class="col-auto">
              <mat-checkbox id="penName" formControlName="penName"></mat-checkbox>
            </div>
          </div>
        </div>
        <div class="col-lg-6 pt-2">
          <h2 class="mt-lg-0 mb-2">Notes</h2>
          <quill-editor [sanitize]="true" formControlName="note"></quill-editor>
          <div class="d-flex align-items-center mt-4 mt-lg-3">
            <h2 class="me-3">Foto</h2>
            <div *ngIf="displaySaveReminder" class="text-danger fw-bold">You changed the foto - don't forget to save!</div>
            <app-reactive-validation-display [control]="formGroup?.get('foto')"></app-reactive-validation-display>
          </div>
          <div class="author-foto-wrapper col-sm-7 col-md-6 col-lg-5 col-xl-4 position-relative d-flex flex-column justify-content-center align-items-center">
            <img *ngIf="imageUrl" [src]="imageUrl" class="author-foto-img" alt="Foto of the Author">
            <a (click)="openFotoUploadDialog()" class="author-foto-change-link" role="button">{{formGroup.get('id')?.value ? 'change foto' : 'upload foto'}}</a>
          </div>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
          <button (click)="navigateBack()" class="btn btn-secondary btn-lg">
            cancel
          </button>
          <button (click)="saveAndNavigateToDetailPage()" class="btn btn-success btn-lg px-4">
            save
          </button>
        </div>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>

// react/src/features/authors/author-edit.tsx
import 'react-quill/dist/quill.snow.css';
import {useParams} from 'react-router-dom';
import {Checkbox, Paper, TextField, ToggleButton, ToggleButtonGroup} from '@mui/material';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import React, {SyntheticEvent, useEffect, useState} from 'react';
import Author from '@local/mock-backend/author/Author';
import {findAuthorById} from '@local/mock-backend/author/author-mock-data';
import {DatePicker, DesktopDatePicker, LocalizationProvider} from '@mui/lab';
import LuxonAdapter from "@date-io/luxon";
import GenderDisplay from '../../shared/GenderDisplay';
import ReactQuill from 'react-quill';

interface AuthorEditState {
  loading: boolean,
  author: Author,
  errors: {
    [key: string]: string | null
  }
  imageUrl?: string
}

const AuthorEdit = () => {
  const [state, setState] = useState<AuthorEditState>({loading: true, author: {}, errors: {}});
  const {id} = useParams();

  useEffect(() => {
    function loadAuthor() {
      const authorId = Number(id);
      console.log("loadAuthor", authorId);
      setState({loading: true, author: {}, errors: {}});

      findAuthorById(authorId).subscribe(
          {
            next: (a: Author) => {
              console.log("findAuthorById SUCCESS", a);
              const imageUrl = URL.createObjectURL(a.foto!);
              setState({loading: false, author: a, errors: {}, imageUrl});
            },
            error: (error: any) => {
              console.log("findAuthorById ERROR", error);
            }
          });
    }

    return loadAuthor();
  }, [id]);

  function handleInputChange(event: SyntheticEvent) {
    const target = event.target as HTMLInputElement;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;

    changeStateField(target.required, name, value);
  }

  function changeStateField(required: boolean, name: string, value: any) {
    console.log("changeStateField", name, value);

    if ((required || name === "birthdate") && !value) {
      state.errors[name] = "Cannot be empty";
      console.log("setting required error message");
    } else {
      state.errors[name] = null;
    }

    if (name === "dateOfDeath") {
      console.log(name + ": " + value?.toFormat("dd.LL.yyyy"));
    }

    setState({
      ...state, author: {...state.author, [name]: value},
    });

    setTimeout(() =>
        console.log(state), 1000);
  }

  function openFotoUploadDialog(){
    console.log(openFotoUploadDialog);
  }

  return (
      <LocalizationProvider dateAdapter={LuxonAdapter}>
        <div className="comp-wrapper">
          <Paper elevation={8} className="app-col">
            <div className="p-2 ms-lg-3 title-row d-flex flex-wrap align-items-center justify-content-between">
              <div className="d-flex align-items-center justify-content-between flex-wrap">
                <div className="d-flex align-items-center">
                  <h1>Author: {state.author?.firstname} {state.author?.lastname}</h1>
                </div>
              </div>
              <button className="btn btn-danger btn-lg me-4">delete</button>
            </div>
            <LoadingIndicatorWrapper loading={state.loading}>
              <form>
                <div className="pb-3" style={{borderTop: "2px solid gray"}}>
                  <div className="row mx-3 gx-0 gx-lg-5">
                    <div className="col-lg-6 pt-2">
                      <h2 className="mb-2">Personal Data</h2>
                      <TextField name="firstname" label="Firstname" value={state.author.firstname} onChange={handleInputChange}
                                 required error={!!state.errors["firstname"]} helperText={state.errors["firstname"]}
                                 variant="outlined" className="w-100"/>
                      <TextField name="lastname" label="Lastname" value={state.author.lastname} onChange={handleInputChange}
                                 required error={!!state.errors["lastname"]} helperText={state.errors["lastname"]}
                                 variant="outlined" className="w-100 mt-4"/>
                      <>
                        <DatePicker value={state.author.birthdate?.toJSDate()}
                                    onChange={(e) => changeStateField(true, "birthdate", e)}
                                    mask="dd.LL.yyyy" inputFormat="dd.LL.yyyy"
                                    renderInput={(props) => (
                                        <TextField {...props} required
                                                   error={!!state.errors["birthdate"]}
                                                   helperText={state.errors["birthdate"]}
                                                   label="Birthdate" variant="outlined" className="w-100 mt-4"/>
                                    )}>
                        </DatePicker>
                        <TextField name="placeOfBirth" label="Place of birth" value={state.author.placeOfBirth} onChange={handleInputChange}
                                   required error={!!state.errors["placeOfBirth"]} helperText={state.errors["placeOfBirth"]}
                                   variant="outlined" className="w-100 mt-4"/>

                        <DesktopDatePicker value={state.author.dateOfDeath ? state.author.dateOfDeath.toJSDate() : null}
                                           onChange={(e) => changeStateField(false, "dateOfDeath", e)}
                                           mask="dd.LL.yyyy" inputFormat="dd.LL.yyyy"
                                           renderInput={(props) => (
                                               <TextField {...props}
                                                          label="Date of death" variant="outlined" className="w-100 mt-4"/>
                                           )}>
                        </DesktopDatePicker>
                        <TextField name="placeOfDeath" label="Place of Death" value={state.author.placeOfDeath} onChange={handleInputChange}
                                   error={!!state.errors["placeOfDeath"]} helperText={state.errors["placeOfDeath"]}
                                   variant="outlined" className="w-100 mt-4"/>

                        <div className="d-flex align-items-center mt-4">
                          <label className="me-3">Gender</label>
                          <ToggleButtonGroup value={state.author.gender} exclusive
                                             onChange={(_$event, value) => changeStateField(true, "gender", value)}
                          >
                            <ToggleButton value="MALE"><GenderDisplay gender="MALE"/></ToggleButton>
                            <ToggleButton value="FEMALE"><GenderDisplay gender="FEMALE"/></ToggleButton>
                            <ToggleButton value="NON_BINARY"><GenderDisplay gender="NON_BINARY"/></ToggleButton>
                          </ToggleButtonGroup>
                        </div>

                        <div className="d-flex align-items-center mt-2">
                          <label htmlFor="pen-name">Pen name</label>
                          <Checkbox id="pen-name" value={state.author.penName} onChange={handleInputChange}/>
                        </div>
                      </>
                    </div>

                    <div className="col-lg-6 pt-2">
                      <h2 className="mt-lg-0 mb-2">Notes</h2>
                      <ReactQuill value={state.author?.note} onChange={(value) => changeStateField(true, "note", value)}
                                  theme="snow" modules={{
                        toolbar: [
                          ['bold', 'italic', 'underline'],
                          [{'header': [1, 2, 3, 4, false]}],
                        ]
                      }}
                      />

                      <div className="d-flex align-items-center mt-4 mt-lg-3">
                        <h2 className="me-3">Foto</h2>
                        <div className="text-danger fw-bold">You changed the foto - don't forget to save!</div>
                        {/*TODO error handling*/}
                        {/*<app-reactive-validation-display [control]="formGroup?.get('foto')"></app-reactive-validation-display>*/}
                      </div>
                      <div
                          className="foto-wrapper col-sm-7 col-md-6 col-lg-5 col-xl-4 position-relative d-flex flex-column justify-content-center align-items-center">
                        <img src={state?.imageUrl} className="author-foto-img" alt="Foto of the Author"/>
                        <a onClick={openFotoUploadDialog} className="author-foto-change-link" role="button">{state.author.id ? 'change foto' : 'upload foto'}</a>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </LoadingIndicatorWrapper>
          </Paper>
        </div>
      </LocalizationProvider>
  )
}

export default AuthorEdit;
