// vue/src/components/authors/AuthorDetail.vue
<template>
  <div class="app-col">
    <div class="title-row-wrapper">
      <div class="title-row">
        <h1 v-if="!isLoading">{{ fullname }}</h1>
      </div>
    </div>

    <div>
      <LoadingIndicatorOverlayWrapper :show-overlay="isLoading" spinner-size="5x">
        <div class="row mx-1 mx-lg-2" style="min-height: 400px;">
          <div class="col-md-8">
            <template v-if="author">
              <div v-if="author?.penName" class="label mt-3"><strong>{{ fullname }}</strong> is a pen name of
                <strong>{{ author.fullRealName }}</strong></div>
              <div class="mt-3">
                <span class="label">Born {{ author?.birthdate?.toFormat("dd.LL.yyyy") }} in {{ author?.placeOfBirth }}</span>
                <span v-if="!author?.dateOfDeath" class="label">&nbsp;&nbsp;(Age {{ author?.age }})</span>
              </div>
              <div v-if="author?.dateOfDeath">
                <span class="label">Died {{ author?.dateOfDeath?.toFormat("dd.LL.yyyy") }}  in {{ author?.placeOfBirth }}</span>
                <span class="label">&nbsp;&nbsp;(Age {{ author?.age }})</span>
              </div>
              <div v-if="author.website" class="mt-3 label">Homepage: <a href="{{author?.website}}">{{ author?.website }}</a></div>
              <div class="label">Genre: {{ author?.genre }}</div>
              <div v-html="author?.note" class="mt-3 note"></div>
            </template>
          </div>
          <div class="col-md-4 d-flex flex-column align-items-center justify-content-start">
            <div class="foto-wrapper">
              <font-awesome-icon v-if="!imageUrl" icon="spinner" size="3x" class="fa-spin mt-5"/>
              <img v-if="imageUrl" :src="imageUrl" class="author-foto-img" alt="Foto of the Author">
            </div>
            <div class="mt-4">
              <h2>Books written by {{ fullname }}</h2>
              <font-awesome-icon v-if="isBooksLoading" icon="spinner" size="3x" class="fa-spin mt-5 ms-3"/>
              <div v-if="!isBooksLoading && books?.length === 0" class="ms-4">
                No books from {{ fullname }} saved - you can add some in the
                <router-link to="/library">Library</router-link>
              </div>
              <ul v-if="!isBooksLoading">
                <li v-for="book of books" :key="book.id">
                  <router-link to="/library/edit/{{book.id}}">
                    {{ book.title }}
                  </router-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
            <button @click="navigateBackToList()" class="btn btn-secondary btn-lg">
              &nbsp;back&nbsp;
            </button>
            <button @click="navigateToEditPage()" class="btn btn-warning btn-lg px-4">
              &nbsp;edit&nbsp;
            </button>
          </div>
        </div>
      </LoadingIndicatorOverlayWrapper>
    </div>
  </div>

</template>

<script setup lang="ts">
import type {ComputedRef, Ref} from 'vue';
import {computed, onMounted, ref} from 'vue';
import type {Author} from '../../../../react/src/mock-backend/author/Author';
import type {Book} from '../../../../react/src/mock-backend/book/Book';
import type {EnrichedAuthor} from '../../../../react/src/mock-backend/author/EnrichedAuthor';
import {findAuthorById} from '../../../../react/src/mock-backend/author/author-mock-data';
import {findBooksOfAuthor} from '../../../../react/src/mock-backend/book/book-mock-data';
import {enrichWithCalculatedFields} from '../../../../react/src/mock-backend/author/author-util';
import LoadingIndicatorOverlayWrapper from '@/components/shared/LoadingIndicatorOverlayWrapper.vue';
import router from '@/router';
import {createImageUrlFromBlob} from '@/util/ImageService';
import './author-detail.scss';

const isLoading = ref(true);
const isBooksLoading = ref(true);
const imageUrl: Ref<string | undefined> = ref(undefined);
const books: Ref<Book[]> = ref([]);
const author: Ref<EnrichedAuthor | null> = ref(null);
const fullname: ComputedRef<string> = computed((): string => `${author.value?.firstname} ${author.value?.lastname}`);

onMounted(() => {
  const id = router.currentRoute.value.params.id
  console.log(`onMounted`, id);
  loadAuthor(Number(id));
  loadBooksForAuthor(Number(id));
})

function loadAuthor(id: number) {
  findAuthorById(id).subscribe({
    next: (a: Author) => {
      console.log("loadAuthor SUCCESS", a);
      isLoading.value = false;
      author.value = enrichWithCalculatedFields(a);
      imageUrl.value = createImageUrlFromBlob(author.value.foto);
    },
  });
}

function loadBooksForAuthor(id: number) {
  isBooksLoading.value = true;
  findBooksOfAuthor(id).subscribe({
    next: (b: Book[]) => {
      console.log("loadBooksForAuthor SUCCESS", b);
      isBooksLoading.value = false;
      books.value = b;
    },
  });
}

function navigateBackToList() {
  console.log("navigateBackToList");
  router.push("/author");
}

function navigateToEditPage() {
  console.log("navigateToEditPage");
  router.push("/author/edit/" + author?.value?.id);
}
</script>

<style scoped>

</style>

// react/src/features/authors/author-detail.tsx
import 'react-quill/dist/quill.snow.css';
import "./author-detail.scss";
import React, {memo, useContext, useEffect, useState} from 'react';
import {Author} from '@local/mock-backend/author/Author';
import {EnrichedAuthor} from '@local/mock-backend/author/EnrichedAuthor';
import {Book} from '@local/mock-backend/book/Book';
import {Paper} from '@mui/material';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import {NavLink, useNavigate, useParams} from 'react-router-dom';
import {findAuthorById} from '@local/mock-backend/author/author-mock-data';
import sanitize from 'sanitize-html';
import {findBooksOfAuthor} from '@local/mock-backend/book/book-mock-data';
import {GlobalMessageContext} from '../../shared/GlobalMessageContext';
import {enrichWithCalculatedFields} from '@local/mock-backend/author/author-util';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faSpinner} from '@fortawesome/free-solid-svg-icons/faSpinner';

interface AuthorDetailState {
  author?: EnrichedAuthor,
  imageUrl?: string
  loading: boolean
  books?: Book[];
  booksLoading: boolean
}

const AuthorDetail = () => {
  console.log("AuthorDetail");
  const [state, setState] = useState<AuthorDetailState>({author: {}, loading: true, booksLoading: true});
  const {id} = useParams();
  const globalMessageContext = useContext(GlobalMessageContext);
  const navigate = useNavigate();
  useEffect(() => {
    const authorId = Number(id);
    loadAuthor();
    loadBooksOfAuthor();

    function loadAuthor() {
      console.log("loadAuthor");
      setState(oldState => ({...oldState, author: {}, loading: true}));

      const defaultOptions = {
        allowedTags: ['b', 'i', 'em', 'strong', 'h1', 'h2', 'h3', 'h4', 'h5'],
      };

      findAuthorById(authorId).subscribe(
        {
          next: (a: Author) => {
            console.log("findAuthorById SUCCESS", a);
            const valid = sanitize(a.note || "", defaultOptions);
            if (!valid) {
              throw new Error("invalid html");
            }
            const imageUrl = URL.createObjectURL(a.foto!);
            setState(oldState => ({...oldState, loading: false, author: enrichWithCalculatedFields(a), imageUrl}));
          },
          error: (error: any) => {
            console.log("findAuthorById ERROR", error);
            globalMessageContext.setMessage({message: "Error loading author", severity: "danger"});
          }
        });
    }

    function loadBooksOfAuthor() {
      console.log("loadBooksOfAuthor");
      setState(oldState => ({...oldState, booksLoading: true}));
      findBooksOfAuthor(authorId).subscribe({
        next: (books: Book[]) => {
          console.log("loadBooksOfAuthor SUCCESS", books);
          setState(oldState => ({...oldState, booksLoading: false, books}));
        },
        error: (error: any) => {
          console.log("loadBooksOfAuthor ERROR", error);
          globalMessageContext.setMessage({message: "Error loading books", severity: "danger"});
        }
      });
    }
  }, []);

  function navigateBackToList() {
    console.log("navigateBackToList");
    navigate("/author");
  }

  function navigateToEditPage() {
    console.log("navigateToEditPage");
    navigate(id!.toString());
  }

  return (
    <div className="comp-wrapper">
      <Paper elevation={8} className="app-col">
        <div className="p-2 ms-lg-3 title-row d-flex flex-wrap align-items-center justify-content-between">
          <div className="d-flex align-items-center flex-wrap">
            <h1>Author {state.author?.firstname} {state.author?.lastname}</h1>
          </div>
        </div>
        <LoadingIndicatorWrapper loading={state.loading}>
          <div style={{borderTop: "2px solid gray"}}>
            <div className="row mx-1 mx-lg-2" style={{minHeight: 400}}>
              <div className="col-md-8">
                {state.author?.penName &&
                  <div className="label mt-3"><strong>{state.author?.firstname + " " + state.author?.lastname}</strong> is a pen name
                    of <strong>{state.author?.fullRealName}</strong></div>}
                <div className="mt-3">
                  <span className="label">Born {state.author?.birthdate?.toFormat("dd.LL.yyyy")} in {state.author?.placeOfBirth}</span>
                  {<span className="label">&nbsp;&nbsp;(Age {state.author?.age})</span>}
                  {state.author?.dateOfDeath && <span className="label">&nbsp;&nbsp;(Age {state.author?.age})</span>}
                </div>
                {state.author?.dateOfDeath && <div>
                  <span className="label">Died {state.author?.dateOfDeath?.toFormat("dd.LL.yyyy")} in {state.author?.placeOfBirth}</span>
                  {<span className="label">&nbsp;&nbsp;(Age {state.author?.age})</span>}
                </div>}
                {state.author?.website &&
                  <div className="mt-3 label">Homepage: <a href={state.author?.website}>{state.author?.website}</a></div>
                }
                <div className="label">Genre: {state.author?.genre}</div>
                <div className="mt-3 note" dangerouslySetInnerHTML={{__html: (state.author?.note || "")}}/>
              </div>
              <div className="col-md-4 d-flex flex-column align-items-center justify-content-start">
                <div className="foto-wrapper">
                  <img src={state.imageUrl} className="author-foto-img" alt="Foto of the Author"/>
                </div>
                <div className="mt-4">
                  <h2>Books written by {state.author?.firstname + " " + state.author?.lastname}</h2>
                  {state.booksLoading && <div className="ms-5 mt-3">
                    <FontAwesomeIcon icon={faSpinner} size={'3x'} className="fa-spin"/>
                  </div>}
                  {!state.booksLoading && state.books?.length === 0 && <div className="ms-4">
                    No books from {state.author?.firstname + " " + state.author?.lastname} saved - you can add some in the&nbsp;
                    <NavLink to="/library">Library</NavLink>
                  </div>}
                  {(!state.booksLoading) && <ul>
                    {state.books?.map(b => <li key={b.id}><NavLink to={"/library/edit/" + b.id}>{b.title}</NavLink></li>)}
                  </ul>}
                </div>
              </div>
            </div>
          </div>
          <div className="row mt-3">
            <div className="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
              <button onClick={() => navigateBackToList()} className="btn btn-secondary btn-lg">
                &nbsp;back&nbsp;
              </button>
              <button onClick={() => navigateToEditPage()} className="btn btn-warning btn-lg px-4">
                &nbsp;edit&nbsp;
              </button>
            </div>
          </div>
        </LoadingIndicatorWrapper>
      </Paper>
    </div>
  )
}

export default memo(AuthorDetail);
