// vue/src/components/authors/AuthorList.vue
<template>
  <div class="app-col">
    <div class="title-row-wrapper">
      <div class="title-row">
        <div class="d-flex align-items-center">
          <h1>Authors</h1>
          <div class="input-group ms-2 ms-lg-5">
            <input @keyup="filter(filterInput)" v-model="filterInput" autofocus class="form-control" placeholder="filter"
                   aria-label="Filter">
            <span class="input-group-text">
              <font-awesome-icon icon="filter" size="lg"/>
            </span>
          </div>
        </div>
        <button @click="navigateToNewAuthor()" class="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">
          add Author
        </button>
      </div>
    </div>
    <div>
      //TODO loading indicator
      <br />
      author table
      <!--      <app-loading-indicator-overlay-wrapper [showOverlay]="!filteredAuthors" spinnerSize="6x">-->
      <!--        <div class="table-wrapper">-->
      <!--          <app-author-table *ngIf="filteredAuthors" [authors]="filteredAuthors"-->
      <!--                            (selectAuthor)="onAuthorSelected($event)"></app-author-table>-->
      <!--        </div>-->
      <!--      </app-loading-indicator-overlay-wrapper>-->
    </div>
  </div>

</template>

<script setup lang="ts">
import type {Author} from '../../../../react/src/mock-backend/author/Author';
import type {EnrichedAuthor} from '../../../../react/src/mock-backend/author/EnrichedAuthor';
import {findAllAuthors} from '../../../../react/src/mock-backend/author/author-mock-data';
import router from '@/router';
import {enrichWithCalculatedFields} from '../../../../react/src/mock-backend/author/author-util';

let author: Author | null = null;
let authors: Author[] = [];
let filteredAuthors: Author[] = [];

const loadAllAuthors = () => {
  findAllAuthors().subscribe({
    next: (authors: Author[]) => {
      console.log("findAll", authors);
      authors = authors.map(a => enrichWithCalculatedFields(a));
      filteredAuthors = authors;
    },
    //TODO error handling?
    // error: (error: HttpErrorResponse) => {
    //   this.globalMessageService.setAlertMessage("danger", "Unable to load Authors: ", error);
    //   console.log("error occured");
    // }
  });
}

const filter = (term: string) => {
  console.log("filter", term);
  filteredAuthors = authors?.filter(a =>
    (a.firstname + " " + a.lastname).toLocaleLowerCase().includes(term) ||
    (a.lastname + " " + a.firstname).toLocaleLowerCase().includes(term)
  );
}

const onAuthorSelected = (author: EnrichedAuthor) => {
  console.log("onAuthorSelected", author);
  router.push('"/author/" + author.id');
}

const navigateToNewAuthor = () => {
  console.log("navigateToNewAuthor");
  router.push("/author/edit/new");
}

</script>

<style scoped>
.table-wrapper {
  min-height: calc(100vh - 190px);
}
</style>

// angular/src/app/features/authors/author-list/author-list.component.ts
import {AfterViewInit, Component, ElementRef, OnInit, ViewChild} from '@angular/core';
import {Author} from '@mock-backend/author/Author';
import {findAllAuthors} from '@mock-backend/author/author-mock-data';
import {GlobalMessageService} from '@core/global-message.service';
import {enrichWithCalculatedFields} from '@mock-backend/author/author-util';
import {Router} from '@angular/router';
import {HttpErrorResponse} from '@angular/common/http';
import {EnrichedAuthor} from '@mock-backend/author/EnrichedAuthor';

@Component({
  selector: 'app-author-list',
  templateUrl: './author-list.component.html',
  styleUrls: ['./author-list.component.scss']
})
export class AuthorListComponent implements OnInit, AfterViewInit {
  @ViewChild('filterInput') filterElement?: ElementRef;

  authors?: EnrichedAuthor[];
  filteredAuthors?: EnrichedAuthor[];

  constructor(private globalMessageService: GlobalMessageService, private router: Router) {
  }

  ngOnInit(): void {
    this.loadAllAuthors();
  }

  ngAfterViewInit(): void {
    this.filterElement?.nativeElement?.focus();
  }

  loadAllAuthors() {
    findAllAuthors().subscribe({
      next: (authors: Author[]) => {
        console.log("findAll", authors);
        this.authors = authors.map(a => enrichWithCalculatedFields(a));
        this.filteredAuthors = this.authors;
      },
      error: (error: HttpErrorResponse) => {
        this.globalMessageService.setAlertMessage("danger", "Unable to load Authors: ", error);
        console.log("error occured");
      }
    });
  }

  filter(term: string) {
    console.log("filter", term);
    term = term.toLowerCase();
    this.filteredAuthors = this.authors?.filter(a =>
      (a.firstname + " " + a.lastname).toLocaleLowerCase().includes(term) ||
      (a.lastname + " " + a.firstname).toLocaleLowerCase().includes(term)
    );
  }

  onAuthorSelected(author: EnrichedAuthor) {
    console.log("onAuthorSelected", author);
    this.router.navigate(["/author/" + author.id]);
  }

  navigateToNewAuthor() {
    console.log("navigateToNewAuthor");
    this.router.navigate(["/author/edit/new"]);
  }
}

<div class="app-col">
  <div class="title-row-wrapper">
    <div class="title-row">
      <div class="d-flex align-items-center">
        <h1>Authors</h1>
        <div class="input-group ms-2 ms-lg-5">
          <!-- TODO fix autofocus when navigating later-->
          <input id="filterInput" #filterInput (keyup)="filter(filterInput.value)" autofocus class="form-control" placeholder="filter" aria-label="Filter">
          <span class="input-group-text"><mat-icon>filter_alt</mat-icon></span>
        </div>
      </div>
      <button (click)="navigateToNewAuthor()" class="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">
        add Author
      </button>
    </div>
  </div>
  <div>
    <app-loading-indicator-overlay-wrapper [showOverlay]="!filteredAuthors" spinnerSize="6x">
      <div id="author-table-wrapper" class="table-wrapper">
        <app-author-table *ngIf="filteredAuthors" [authors]="filteredAuthors" (selectAuthor)="onAuthorSelected($event)"></app-author-table>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>
