// angular/src/app/shared/header/header.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss']
})
export class HeaderComponent implements OnInit {
  isMenuCollapsed = true;

  constructor() {
  }

  ngOnInit(): void {
  }

}

<nav class="navbar navbar-expand-md navbar-light shadow p-0">
  <a routerLink="/" class="navbar-brand d-flex align-items-center ms-0 ms-md-3 me-0">
    <img src="/assets/demo-bookstore-gold-48px.png" class="logo-image" alt="logo">
    <img src="/assets/angular-gold-18px.png" class="logo-image-appendix-small" alt="logo appendix">
  </a>
  <button class="navbar-toggler m-2" (click)="isMenuCollapsed=!isMenuCollapsed" type="button" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navbarNav" class="navbar-collapse justify-content-between align-items-center"
       (click)="isMenuCollapsed=true" [hidden]="isMenuCollapsed">
    <ul class="navbar-nav w-100 ms-0 ms-lg-2">
      <li class="nav-item">
        <a routerLink="/home" routerLinkActive="active" class="nav-link">
          Home
        </a>
      </li>
      <li class="nav-item">
        <a routerLink="/your-books" routerLinkActive="active" class="nav-link">
          Your Books
        </a>
      </li>
      <li class="nav-item">
        <a routerLink="/library" routerLinkActive="active" class="nav-link">
          Library
        </a>
      </li>
      <li class="nav-item">
        <a routerLink="/authors" routerLinkActive="active" class="nav-link">
          Authors
        </a>
      </li>
      <li class="d-md-none mb-2 logout-link-mobile">
        <button (click)="handleLogoutClick()" class="btn btn-link link-dark ms-2 fs-5 text-decoration-none">log
          out <span class="fw-bold">"{{(userService.authentication$ | async)}}"</span></button>
      </li>
    </ul>
    <div class="btn-group me-3 d-none d-lg-block" dropdown>
      <div id="button-basic" dropdownToggle class="cursor-pointer" type="button" aria-controls="dropdown-basic">
        <fa-icon [icon]="iconUserCircle"></fa-icon>
      </div>
      <div id="dropdown-basic" *dropdownMenu class="dropdown-menu dropdown-menu-right"
           role="menu" aria-labelledby="button-basic">
        <div class="d-flex flex-column align-items-center fs-4 mx-3">
          <div>logged in as</div>
          <div class="fw-bold">"{{(userService.authentication$ | async)}}"</div>
          <button (click)="handleLogoutClick()" class="btn btn-secondary my-2">log out</button>
        </div>
      </div>
    </div>
  </div>


  <!--        <li class="d-md-none mb-3 logout-link-mobile">-->
  <!--          <button (click)="handleLogoutClick()" class="my-2 btn btn-link link-dark fs-5 text-decoration-none">log-->
  <!--            out <span class="fw-bold">"{{(userService.authentication$ | async)}}</span></button>-->
  <!--        </li>-->
  <!--        <div class="d-none d-md-block ms-md-auto me-3">-->
  <!--          <i class="fa fa-user-circle fa-2x"></i>-->
  <!--          &lt;!&ndash;        <div id="dropdown-basic-button" title={<FontAwesomeIcon icon={faUserCircle} size={'2x'}/>}>&ndash;&gt;-->

  <!--          &lt;!&ndash;        </div>&ndash;&gt;-->
  <!--        </div>-->

  <!--      <div *ngIf="(userService.authentication$ | async ) as userWrapper" (click)="userService.logout()"-->
  <!--           class="logout-link ms-md-auto me-3 d-flex align-items-center">-->
  <!--        <span class="d-inline d-md-none d-xl-inline"><span class="d-inline d-md-none"> logout</span> {{userWrapper.user?.username}}</span>-->
  <!--        <i matTooltip="log out" class="fa fa-sign-out-alt fa-lg ms-2" aria-hidden="true"></i>-->
  <!--      </div>-->
  <!--      </ul>-->
  <!--  </div>-->
</nav>

// vue/src/components/Header.vue
<template>
  <header class="navbar fixed-top navbar-expand-md navbar-light shadow p-0">
    <a routerLink="/home" class="navbar-brand d-flex align-items-center ms-0 ms-md-3 me-0">
      <img src="../assets/demo-bookstore-gold-48px.png" class="logo-image" alt="logo">
      <img src="../assets/vuejs-gold-18px.png" class="logo-image-appendix-small" alt="logo appendix">
    </a>
    <!--    <button class="navbar-toggler me-2" (click)="isMenuCollapsed=!isMenuCollapsed" type="button" aria-expanded="false" aria-label="Toggle navigation">-->
    <button class="navbar-toggler me-2" type="button" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="navbarNav" class="navbar-collapse justify-content-between align-items-center mt-1">
      <!--      (click)="isMenuCollapsed=true" [hidden]="isMenuCollapsed">-->
      <ul class="navbar-nav w-100 ms-0 ms-lg-2">
        <li class="nav-item">
          <a routerLink="/home" routerLinkActive="active" class="nav-link">
            Home
          </a>
        </li>
        <li class="nav-item">
          <a routerLink="/your-books" routerLinkActive="active" class="nav-link">
            Your Books
          </a>
        </li>
        <li class="nav-item">
          <a routerLink="/library" routerLinkActive="active" class="nav-link">
            Library
          </a>
        </li>
        <li class="nav-item">
          <a routerLink="/author" routerLinkActive="active" class="nav-link">
            Authors
          </a>
        </li>
        <li class="d-md-none mb-2 logout-link-mobile">
          <!--            TODO USER SERVICE-->
          <!--          <button (click)="handleLogoutClick()" class="btn btn-link btn-lg link-dark fs-5 text-decoration-none">log-->
          <!--            out <span class="fw-bold">"{{(userService.authentication$ | async)}}"</span></button>-->
        </li>
      </ul>
      <!--      <div class="btn-group me-3 d-none d-lg-block" dropdown>-->
      <!--        <div id="button-basic" dropdownToggle class="cursor-pointer" type="button" aria-controls="dropdown-basic">-->
      <!--          <fa-icon [icon]="iconUserCircle"></fa-icon>-->
      <!--        </div>-->
      <!--        <div id="dropdown-basic" *dropdownMenu class="dropdown-menu dropdown-menu-right"-->
      <!--             role="menu" aria-labelledby="button-basic">-->
      <!--          <div class="d-flex flex-column align-items-center fs-4 mx-3">-->
      <!--            <div>logged in as</div>-->
      <!--&lt;!&ndash;            TODO USER SERVICE&ndash;&gt;-->
      <!--&lt;!&ndash;            <div class="fw-bold">"{{(userService.authentication$ | async)}}"</div>&ndash;&gt;-->
      <!--            <button (click)="handleLogoutClick()" class="btn btn-secondary my-2">log out</button>-->
      <!--          </div>-->
      <!--        </div>-->
      <!--      </div>-->
    </div>
  </header>

</template>

<script>
import './Header.scss';

export default {}
</script>

<style scoped>

</style>
