// vue/src/components/authors/AuthorDetail.vue
<template>
  <div class="app-col">
    <div class="title-row-wrapper">
      <div class="title-row">
        <h1 v-if="!isLoading">{{ fullname }}</h1>
      </div>
    </div>

    <div>
      <LoadingIndicatorOverlayWrapper :show-overlay="isLoading" spinner-size="5x">
        <div class="row mx-1 mx-lg-2" style="min-height: 400px;">
          <div class="col-md-8">
            <template v-if="author">
              <div v-if="author?.penName" class="label mt-3"><strong>{{ fullname }}</strong> is a pen name of
                <strong>{{ author.fullRealName }}</strong></div>
              <div class="mt-3">
                <span class="label">Born {{ author?.birthdate?.toFormat("dd.LL.yyyy") }} in {{ author?.placeOfBirth }}</span>
                <span v-if="!author?.dateOfDeath" class="label">&nbsp;&nbsp;(Age {{ author?.age }})</span>
              </div>
              <div v-if="author?.dateOfDeath">
                <span class="label">Died {{ author?.dateOfDeath?.toFormat("dd.LL.yyyy") }}  in {{ author?.placeOfBirth }}</span>
                <span class="label">&nbsp;&nbsp;(Age {{ author?.age }})</span>
              </div>
              <div v-if="author.website" class="mt-3 label">Homepage: <a href="{{author?.website}}">{{ author?.website }}</a></div>
              <div class="label">Genre: {{ author?.genre }}</div>
              <div v-html="author?.note" class="mt-3 note"></div>
            </template>
          </div>
          <div class="col-md-4 d-flex flex-column align-items-center justify-content-start">
            <div class="foto-wrapper">
              <font-awesome-icon v-if="!imageUrl" icon="spinner" size="3x" class="fa-spin mt-5"/>
              <img v-if="imageUrl" :src="imageUrl" class="author-foto-img" alt="Foto of the Author">
            </div>
            <div class="mt-4">
              <h2>Books written by {{ fullname }}</h2>
              <font-awesome-icon v-if="isBooksLoading" icon="spinner" size="3x" class="fa-spin mt-5 ms-3"/>
              <div v-if="!isBooksLoading && books?.length === 0" class="ms-4">
                No books from {{ fullname }} saved - you can add some in the
                <router-link to="/library">Library</router-link>
              </div>
              <ul v-if="!isBooksLoading">
                <li v-for="book of books" :key="book.id">
                  <router-link to="/library/edit/{{book.id}}">
                    {{ book.title }}
                  </router-link>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row mt-3">
          <div class="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
            <button @click="navigateBackToList()" class="btn btn-secondary btn-lg">
              &nbsp;back&nbsp;
            </button>
            <button @click="navigateToEditPage()" class="btn btn-warning btn-lg px-4">
              &nbsp;edit&nbsp;
            </button>
          </div>
        </div>
      </LoadingIndicatorOverlayWrapper>
    </div>
  </div>

</template>

<script setup lang="ts">
import type {ComputedRef, Ref} from 'vue';
import {computed, onMounted, ref} from 'vue';
import type {Author} from '../../../../react/src/mock-backend/author/Author';
import type {Book} from '../../../../react/src/mock-backend/book/Book';
import type {EnrichedAuthor} from '../../../../react/src/mock-backend/author/EnrichedAuthor';
import {findAuthorById} from '../../../../react/src/mock-backend/author/author-mock-data';
import {findBooksOfAuthor} from '../../../../react/src/mock-backend/book/book-mock-data';
import {enrichWithCalculatedFields} from '../../../../react/src/mock-backend/author/author-util';
import LoadingIndicatorOverlayWrapper from '@/components/shared/LoadingIndicatorOverlayWrapper.vue';
import router from '@/router';
import {createImageUrlFromBlob} from '@/util/ImageService';
import './author-detail.scss';

const isLoading = ref(true);
const isBooksLoading = ref(true);
const imageUrl: Ref<string | undefined> = ref(undefined);
const books: Ref<Book[]> = ref([]);
const author: Ref<EnrichedAuthor | null> = ref(null);
const fullname: ComputedRef<string> = computed((): string => `${author.value?.firstname} ${author.value?.lastname}`);

onMounted(() => {
  const id = router.currentRoute.value.params.id
  console.log(`onMounted`, id);
  loadAuthor(Number(id));
  loadBooksForAuthor(Number(id));
})

function loadAuthor(id: number) {
  findAuthorById(id).subscribe({
    next: (a: Author) => {
      console.log("loadAuthor SUCCESS", a);
      isLoading.value = false;
      author.value = enrichWithCalculatedFields(a);
      imageUrl.value = createImageUrlFromBlob(author.value.foto);
    },
  });
}

function loadBooksForAuthor(id: number) {
  isBooksLoading.value = true;
  findBooksOfAuthor(id).subscribe({
    next: (b: Book[]) => {
      console.log("loadBooksForAuthor SUCCESS", b);
      isBooksLoading.value = false;
      books.value = b;
    },
  });
}

function navigateBackToList() {
  console.log("navigateBackToList");
  router.push("/author");
}

function navigateToEditPage() {
  console.log("navigateToEditPage");
  router.push("/author/edit/" + author?.value?.id);
}
</script>

<style scoped>

</style>

// angular/src/app/features/authors/author-detail/author-detail.component.ts
import {Component, OnInit} from '@angular/core';
import Author from '@mock-backend/author/Author';
import {ActivatedRoute, Router} from '@angular/router';
import {findAuthorById} from '@mock-backend/author/author-mock-data';
import {enrichWithCalculatedFields} from '@mock-backend/author/author-util';
import {ImageService} from '../image.service';
import {SafeUrl} from '@angular/platform-browser';
import {GlobalMessageService} from '@core/global-message.service';
import {Book} from '@mock-backend/book/Book';
import {findBooksOfAuthor} from '@mock-backend/book/book-mock-data';
import {HttpErrorResponse} from '@angular/common/http';
import {EnrichedAuthor} from '@mock-backend/author/EnrichedAuthor';

@Component({
  selector: 'app-author-detail',
  templateUrl: './author-detail.component.html',
  styleUrls: ['./author-detail.component.scss']
})
export class AuthorDetailComponent implements OnInit {
  isLoading = false;
  isBooksLoading = false;
  authorId?: number;
  author?: EnrichedAuthor;
  imageUrl?: SafeUrl;
  books?: Book[];

  constructor(private router: Router, private activatedRoute: ActivatedRoute, private globalMessageService: GlobalMessageService,
              private authorService: ImageService) {
  }

  ngOnInit(): void {
    this.activatedRoute.params.subscribe(params => {
      const authorId = params["id"];
      console.log("params", params, authorId);
      this.loadAuthor(Number(authorId));
      this.loadBooksForAuthor(Number(authorId));
    });
  }

  get fullname() {
    return this.author?.firstname + " " + this.author?.lastname;
  }

  //TODO extract past of it to shared service
  loadAuthor(id: number) {
    this.authorId = id;
    this.isLoading = true;
    findAuthorById(id).subscribe({
      next: (author: Author) => {
        console.log("loadAuthor SUCCESS", author);
        this.isLoading = false;
        this.author = enrichWithCalculatedFields(author);
        this.imageUrl = this.authorService.createImageUrlFromBlob(author.foto!);
      },
      error: (error: HttpErrorResponse) => {
        this.globalMessageService.setAlertMessage("danger", "Unable to load Author: ", error);
        console.log("loadAuthor ERROR", error);
        this.isLoading = false;
      }
    });
  }

  loadBooksForAuthor(id: number) {
    this.isBooksLoading = true;
    findBooksOfAuthor(id).subscribe({
      next: (books: Book[]) => {
        console.log("loadBooksForAuthor SUCCESS", books);
        this.isBooksLoading = false;
        this.books = books;
      },
      error: (error: HttpErrorResponse) => {
        this.globalMessageService.setAlertMessage("danger", "Unable to load Books of Author: ", error);
        console.log("loadBooksForAuthor ERROR", error);
        this.isBooksLoading = false;
      }
    });
  }

  navigateToMasterPage() {
    this.router.navigate(["/author"]);
  }

  navigateToEditPage() {
    this.router.navigate(["/author/edit/" + this.authorId]);
  }

}

<div class="app-col mat-elevation-z8">
  <div class="p-2 ms-lg-3">
    <div class="d-flex align-items-center justify-content-between flex-wrap" style="min-height: 48px;">
      <h1>Author <span *ngIf="!isLoading" class="h1">{{fullname}}</span></h1>
    </div>
  </div>

  <div style="border-top: 2px solid gray;">
    <app-loading-indicator-overlay-wrapper [showOverlay]="isLoading" spinnerSize="6x">
      <div class="row mx-1 mx-lg-2" style="min-height: 400px;">
        <div class="col-md-8">
          <ng-container *ngIf="author">
            <div *ngIf="author?.penName" class="label mt-3"><strong>{{fullname}}</strong> is a pen name of <strong>{{author.fullRealName}}</strong></div>
            <div class="mt-3">
              <span class="label">Born {{author?.birthdate?.toFormat("dd.LL.yyyy")}} in {{author?.placeOfBirth}}</span>
              <span *ngIf="!author?.dateOfDeath" class="label">&nbsp;&nbsp;(Age {{author?.age}})</span>
            </div>
            <div *ngIf="author?.dateOfDeath">
              <span class="label">Died {{author?.dateOfDeath?.toFormat("dd.LL.yyyy")}}  in {{author?.placeOfBirth}}</span>
              <span class="label">&nbsp;&nbsp;(Age {{author?.age}})</span>
            </div>
            <div *ngIf="author.website" class="mt-3 label">Homepage: <a href="{{author?.website}}">{{author?.website}}</a></div>
            <div class="label">Genre: {{author?.genre}}</div>
            <div class="mt-3 note" [innerHTML]="author?.note"></div>
          </ng-container>
        </div>
        <div class="col-md-4 d-flex flex-column align-items-center justify-content-start">
          <div class="foto-wrapper">
            <img *ngIf="imageUrl" [src]="imageUrl" class="author-foto-img" alt="Foto of the Author">
          </div>
          <div class="mt-4">
            <h2>Books written by {{fullname}}</h2>
            <div *ngIf="isBooksLoading" class="ms-5 mt-3">
              <fa-icon icon="spinner" size="3x" [classes]="['fa-spin']"></fa-icon>
            </div>
            <div *ngIf="!isBooksLoading && books?.length === 0" class="ms-4">
              No books from {{fullname}} saved - you can add some in the <a routerLink="/library"> Library</a>
            </div>
            <ul *ngIf="!isBooksLoading">
              <li *ngFor="let book of books"><a routerLink="/library/edit/{{book.id}}">{{book.title}}</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
          <button (click)="navigateToMasterPage()" class="btn btn-secondary btn-lg">
            &nbsp;back&nbsp;
          </button>
          <button (click)="navigateToEditPage()" class="btn btn-warning btn-lg px-4">
            &nbsp;edit&nbsp;
          </button>
        </div>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>
