// react/src/features/yourBooks/yourBooksList.tsx
import React, {ChangeEvent, useContext, useEffect, useRef, useState} from 'react';
import {Paper} from '@mui/material';
import {faFilter, faInfo} from '@fortawesome/free-solid-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {NavLink} from 'react-router-dom';
import ApplicationContext from '../../shared/ApplicationContext';
import BookCard from './book-card';
import {enrichBookWithUserAssignments, EnrichedBook} from '../../mock-backend/util/book-utils';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import {findBooksForUser} from '../../mock-backend/book/book-mock-data';
import {Book} from '../../mock-backend/book/Book';
import {UserBookAssignmentStatus} from '../../mock-backend/user/user-book-assignment-status';
import {updateStatus} from '../../mock-backend/user/user-book-assignment-mockservice';

interface YourBooksListState {
  loading: boolean,
  books: EnrichedBook[],
  filteredBooks: EnrichedBook[],
  searchTerm: string
}

const YourBooksList = () => {
  console.log("Library");
  const applicationContextRef = useRef(useContext(ApplicationContext));
  const [state, setState] = useState<YourBooksListState>({loading: true, books: [], filteredBooks: [], searchTerm: ""})

  useEffect(() => {
    console.log("useEffect running - should never rerun, since the dependencies-array is empty - loading books");
    findBooksForUser(applicationContextRef.current.user!).subscribe(
      {
        next: (results: Book[]) => {
          let books = results.map(b => enrichBookWithUserAssignments(b, applicationContextRef.current.user!));
          books = books.filter(b => b.assignmentStatus !== "default");
          console.log("findBooksForUser SUCCESS", books);
          setState({
            loading: false,
            searchTerm: "",
            books,
            filteredBooks: [...books]
          });
        },
        error: (error: any) => {
          console.log("findBooksForUser ERROR", error);
          setState({loading: false, searchTerm: "", books: [], filteredBooks: []})
        }
      });
  }, []); // runs exactly once, because the deps array is empty, therefor it will never be re-evaluated#

  function handleFilterKeyup(event: ChangeEvent<HTMLInputElement>) {
    const searchTerm = (event.target as HTMLInputElement).value.toLowerCase();
    const filteredBooks = state.books.filter((b: EnrichedBook) => b.title?.toLocaleLowerCase().includes(searchTerm));
    setState({...state, filteredBooks, searchTerm})
  }

  function handleAssignmentStatusChange(book: EnrichedBook, stat: UserBookAssignmentStatus) {
    console.log("YourBookList: statusChanged received", book, stat);
    updateStatus(applicationContextRef.current.user!, book.id!, stat);
  }

  return (
    <div className="comp-wrapper">
      <Paper elevation={8} className="app-col">
        <div className="title-row">
          <div className="d-flex align-items-center justify-content-between flex-wrap">
            <div className="d-flex align-items-center">
              <h1>Your&nbsp;Books</h1>
              <div className="input-group ms-2 ms-lg-5">
                <input value={state.searchTerm} onChange={(e) => handleFilterKeyup(e)} className="form-control" placeholder="filter"
                       aria-label="Filter"/>
                <span className="input-group-text"><FontAwesomeIcon icon={faFilter}/></span>
              </div>
            </div>
          </div>
          <div className="ms-2 me-4 add-more-books-label">
            <FontAwesomeIcon icon={faInfo} className="me-1"/>
            You can find more books in our <NavLink to="/library">Library</NavLink>
          </div>
        </div>
        <div>
          <LoadingIndicatorWrapper loading={state.loading}>
            <div className="row mx-1 mx-lg-2 justify-content-around pb-4" style={{minHeight: 400}}>
              {state.filteredBooks.map((b) => (
                <div key={b.id} className="col-auto g-4 book-card-wrap">
                  <BookCard key={b.id} book={b} changeStatus={handleAssignmentStatusChange}/>
                </div>
              ))}
            </div>
          </LoadingIndicatorWrapper>
        </div>
      </Paper>
    </div>
  )
};

export default YourBooksList;

// angular/src/app/features/your-books/your-books-list/your-books-list.component.ts
import {AfterViewInit, Component, ElementRef, OnInit, ViewChild} from '@angular/core';
import {BehaviorSubject, combineLatest, map, Observable} from 'rxjs';
import {Book} from '@mock-backend/book/Book';
import {findBooksForUser} from '@mock-backend/book/book-mock-data';
import {MatDialog} from '@angular/material/dialog';
import {BookDetailDialogWrapperComponent} from '@shared/book-detail-dialog-wrapper/book-detail-dialog-wrapper.component';
import {Router} from '@angular/router';
import {UserService} from '@core/user.service';
import {UserBookAssignmentStatus} from '@mock-backend/user/user-book-assignment-status';
import {updateStatus} from '@mock-backend/user/user-book-assignment-mockservice';
import {enrichBookWithUserAssignments, EnrichedBook} from '@mock-backend/util/book-utils';

@Component({
  selector: 'app-your-books-list',
  templateUrl: './your-books-list.component.html',
  styleUrls: ['./your-books-list.component.scss']
})
export class YourBooksListComponent implements OnInit, AfterViewInit {
  @ViewChild('filterInput') filterElement?: ElementRef;

  filterByName$ = new BehaviorSubject("");
  filteredBooks$?: Observable<EnrichedBook[]>

  constructor(private matDialog: MatDialog, private router: Router, private userService: UserService) {
  }

  ngOnInit(): void {
    this.filteredBooks$ = combineLatest([this.filterByName$, findBooksForUser(this.userService.authentication$.getValue())]).pipe(
      map((combination: any) => {
        const filterTerm = combination[0].toLowerCase();
        const books = combination[1].map((b: Book) => enrichBookWithUserAssignments(b, this.userService.authentication$.getValue()));

        console.log(books);
        return books.filter((b: EnrichedBook) => b.title?.toLocaleLowerCase().includes(filterTerm) && b.assignmentStatus !== 'default');
      }),
    );
  }

  ngAfterViewInit(): void {
    this.filterElement?.nativeElement.focus;
  }

  filter(term: string) {
    this.filterByName$.next(term);
  }

  openBookDetail(book: Book) {
    this.matDialog.open(BookDetailDialogWrapperComponent, {
      data: {book},
      maxHeight: "70vh",
      maxWidth: "900px"
    }).afterClosed().subscribe((result) => {
      if (result?.openEditPage) {
        this.router.navigate(["/library/edit", book.id]);
      }
    });
  }

  handleStatusChanged(event: { book: Book, status: UserBookAssignmentStatus }) {
    updateStatus(this.userService.authentication$.getValue(), event.book.id!, event.status);
  }
}

<div class="app-col mat-elevation-z8">
  <div class="p-2 ms-lg-3">
    <div class="d-flex align-items-center justify-content-between flex-wrap">
      <div class="d-flex align-items-center">
        <h1>Your&nbsp;Books</h1>
        <div class="input-group ms-2 ms-lg-5">
          <input #searchTerm (keyup)="filter(searchTerm.value)" autofocus class="form-control" placeholder="type to filter" aria-label="Filter">
          <span class="input-group-text"><mat-icon>filter_alt</mat-icon></span>
        </div>
      </div>
      <div class="ms-2 me-4 add-more-books-label">
        <fa-icon icon="info" ></fa-icon>
        You can find more books in our <a routerLink="/library"> Library</a>
      </div>
    </div>
  </div>
  <!--  // This little trick ensures that the *ngIf always returns true and therefore the content inside is rendered-->
  <!--  // see https://medium.com/@yurykatkov/how-to-avoid-multiple-async-pipes-in-angular-ff0d51a8d368-->
  <!--  // NGRX has ngrxLet for that - unfortunately there is no equivalent for vanilla Angular-->
  <!--  // I created a feature request for this: https://github.com/angular/angular/issues/44667-->
  <div *ngIf="{filteredBooks: (filteredBooks$ | async)} as obs" style="border-top: 2px solid gray;">
    <app-loading-indicator-overlay-wrapper [showOverlay]="!obs.filteredBooks" spinnerSize="6x">

      <div class="row mx-1 mx-lg-2 justify-content-around pb-4" style="min-height: 300px;">
        <div *ngFor="let book of obs.filteredBooks" class="col-auto g-4 book-card-wrap">
          <app-book-card [book]="book" (openDetail)="openBookDetail($event)" (statusChanged)="handleStatusChanged($event)"></app-book-card>
        </div>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>
