// angular/src/app/features/library/book-edit/book-edit.component.ts
import {Component, OnInit} from '@angular/core';
import {FormControl, FormGroup, Validators} from '@angular/forms';
import {createOrUpdateBook, deleteBook, findBookById} from '@mock-backend/book/book-mock-data';
import {ActivatedRoute, Router} from '@angular/router';
import {GlobalMessageService} from '@core/global-message.service';
import {DateTime} from 'luxon';
import {Book} from '@mock-backend/book/Book';
import {ImageService} from '@app/features/authors/image.service';
import {SafeUrl} from '@angular/platform-browser';
import {ImageCropperDialogComponent} from '@app/features/authors/image-cropper-dialog/image-cropper-dialog.component';
import {MatDialog} from '@angular/material/dialog';
import Author from '@mock-backend/author/Author';
import {findAllAuthors} from '@mock-backend/author/author-mock-data';
import {Observable} from 'rxjs';
import {enrichBookWithUserAssignments} from '@core/book-utils';
import {UserService} from '@core/user.service';

@Component({
  selector: 'app-book-edit',
  templateUrl: './book-edit.component.html',
  styleUrls: ['./book-edit.component.scss']
})
export class BookEditComponent implements OnInit {
  isLoading = false;
  imageUrl?: SafeUrl;
  authors$?: Observable<Author[]>;
  formGroup = new FormGroup({
        id: new FormControl(null, Validators.required),
        title: new FormControl(null, Validators.required),
        subtitle: new FormControl(null),
        firstPublished: new FormControl(null, Validators.required),
        series: new FormControl(null),
        numberWithinSeries: new FormControl(null),
        genre: new FormControl(null, Validators.required),

        authorFullName: new FormControl(null, Validators.required),
        authorId: new FormControl(null, Validators.required),

        description: new FormControl(null, Validators.required),
        image: new FormControl(null, Validators.required),
      }
  );
  displaySaveReminder = false;

  constructor(private activatedRoute: ActivatedRoute, private globalMessageService: GlobalMessageService,
              private imageService: ImageService, private router: Router, private matDialog: MatDialog, private userService: UserService) {
    this.activatedRoute.params.subscribe(
        params => {
          const id = params['id'];
          if (id === "new") {
            this.isLoading = false;
          } else {
            this.loadBook(Number(id));
          }
        }
    )
  }

  ngOnInit(): void {
    this.authors$ = findAllAuthors();
  }

  get id() {
    return this.formGroup.get("id")?.value;
  }

  get title() {
    return this.formGroup.get("title")?.value;
  }

  private loadBook(id: number) {
    this.isLoading = true;
    findBookById(id).subscribe({
      next: (book: Book) => {
        console.log("loadAuthor SUCCESS", book);
        this.isLoading = false;
        book = enrichBookWithUserAssignments(book, this.userService.authentication$.getValue())
        this.formGroup.patchValue(book);
        //TODO come back and check for fixes - this is just a workaround for a framework bug
        this.formGroup.patchValue({firstPublished: DateTime.fromJSDate(book.firstPublished.toJSDate())});
        this.imageUrl = this.imageService.createImageUrlFromBlob(book.image);

      },
      error: (error) => {
        this.globalMessageService.setAlertMessage("danger", "Unable to load Author: ", error);
        console.log("loadAuthor ERROR", error);
        this.isLoading = false;
      }
    });
  }


  deleteBook() {
    console.log("deleteBook");
    deleteBook(Number(this.id)).subscribe({
          next: () => {
            console.log("deleteBook SUCCESS");
            this.router.navigate(["/library"])
            this.globalMessageService.setAlertMessage("info", "Successfully deleted " + this.title);
          },
          error: (error) => {
            console.log("deleteBook ERROR", error);
            this.globalMessageService.setAlertMessage("danger", "Unable to delete Book: ", error);
          }
        }
    );
  }

  navigateBack() {
    history.back();
  }

  saveAndNavigateBack() {
    console.log("saveAndNavigateToDetailPage");

    if (this.formGroup.valid) {
      console.log('save', this.formGroup.value);
      createOrUpdateBook(this.formGroup.getRawValue()).subscribe(
          (book: Book) => {
            console.log('createOrUpdateBook SUCCESS', book);
            history.back();
            this.globalMessageService.setAlertMessage("info", "Book saved!");
          }, (error: any) => {
            console.log("createOrUpdateBook ERROR", error);
            this.globalMessageService.setAlertMessage("danger", "Book saving failed", error);
          });
    } else {
      console.log('formgroup is not valid', this.formGroup);
      this.formGroup.markAllAsTouched();
    }
  }

  openFotoUploadDialog() {
    this.matDialog
        .open(ImageCropperDialogComponent, {height: "550px"})
        .afterClosed()
        .subscribe((imageBlob: Blob) => {
          if (imageBlob) {
            console.log("image chosen", imageBlob);
            this.imageUrl = this.imageService.createImageUrlFromBlob(imageBlob);
            this.formGroup.patchValue({image: imageBlob})
            console.log("this.imageUrl ", this.imageUrl);
            if (this.formGroup.get("id")?.value) {
              this.displaySaveReminder = true;
            }
          }
        });
  }

  clearInputIfNoAuthorWasSelected($event: FocusEvent, allAuthors?: Author[] | null) {
    const inputElement = $event.target as HTMLInputElement;
    const newAuthorFullname = inputElement.value;
    const index = allAuthors?.map(a => a.firstname + " " + a.lastname).indexOf(newAuthorFullname);
    if (index === -1) {
      console.log("no author was selected, clearing the input");
      this.formGroup.controls['authorId'].setValue(null);
      this.formGroup.controls['authorFullName'].setValue(null);
    } else {
      const selectedAuthor = allAuthors![index!];
      this.formGroup.controls['authorId'].setValue(selectedAuthor.id);
    }
  }

}

<div class="app-col mat-elevation-z8">
  <div class="p-2 ms-lg-3">
    <div class="d-flex align-items-center justify-content-between flex-wrap" style="min-height: 48px;">
      <h1 *ngIf="!isLoading && !formGroup.get('id')?.value">New Author</h1>
      <h1 *ngIf="!isLoading && formGroup.get('id')?.value">
        <span class="d-none d-lg-inline h1">Book: </span>
        <span class="h1">{{title}}</span>
      </h1>
      <button *ngIf="formGroup.get('id')?.value" (confirm)="deleteBook()" class="btn btn-danger btn-lg me-2 me-lg-4"
              appConfirmation confirmTitle="Delete Author" confirmButtonText="delete" confirmButtonType="danger"
              confirmMessage="Are you sure that you want to delete <strong>{{title}}</strong>?<br />This action cannot be undone!"
      >delete
      </button>
    </div>
  </div>

  <div [formGroup]="formGroup" style="border-top: 2px solid gray;">
    <app-loading-indicator-overlay-wrapper [showOverlay]="isLoading" spinnerSize="6x">
      <div class="row mx-3 gx-0 gx-lg-5">
        <div class="col-lg-6 pt-2">
          <h2 class="mb-2">Personal Data</h2>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Title</mat-label>
            <input matInput placeholder="Title" formControlName="title" required>
            <mat-error>input required</mat-error>
          </mat-form-field>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Subtitle</mat-label>
            <input matInput placeholder="Subtitle" formControlName="subtitle">
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field *ngIf="{authors: authors$ | async} as obs" class="example-full-width w-100" appearance="outline">
            <mat-label>Author</mat-label>
            <input (blur)="clearInputIfNoAuthorWasSelected($event, obs?.authors)" [matAutocomplete]="authorAutocomplete" formControlName="authorFullName"
                   placeholder="Author auswählen" aria-label="Author" matInput>
            <mat-autocomplete #authorAutocomplete="matAutocomplete">
              <mat-option *ngFor="let author of obs?.authors" value="{{author.firstname}} {{author.lastname}}">
                {{author.firstname}} {{author.lastname}}
              </mat-option>
            </mat-autocomplete>
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field class="w-100" appearance="outline">
            <mat-label>First published</mat-label>
            <input matInput [matDatepicker]="firstPublishedPicker" formControlName="firstPublished">
            <mat-datepicker-toggle matSuffix [for]="firstPublishedPicker"></mat-datepicker-toggle>
            <mat-datepicker #firstPublishedPicker></mat-datepicker>
            <mat-error>input required</mat-error>
          </mat-form-field>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Series</mat-label>
            <input matInput placeholder="Series" formControlName="series">
            <mat-error>input required</mat-error>
          </mat-form-field>
          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Book in Series</mat-label>
            <input matInput placeholder="Book in Series" formControlName="numberWithinSeries" type="number">
            <mat-error>input required</mat-error>
          </mat-form-field>

          <mat-form-field class="w-100" appearance="outline">
            <mat-label>Genre</mat-label>
            <input matInput placeholder="Genre" formControlName="genre" required>
            <mat-error>input required</mat-error>
          </mat-form-field>

          <!--          TODO search and set author-->

        </div>
        <div class="col-lg-6 pt-2">
          <h2 class="mt-lg-0 mb-2">Description</h2>
          <quill-editor [sanitize]="true" formControlName="description"></quill-editor>
          <div class="d-flex align-items-center mt-4 mt-lg-3">
            <h2 class="me-3">Cover</h2>
            <div *ngIf="displaySaveReminder" class="text-danger fw-bold">You changed the image - don't forget to save!</div>
            <app-reactive-validation-display [control]="formGroup?.get('image')"></app-reactive-validation-display>
          </div>
          <div class="foto-wrapper col-sm-7 col-md-6 col-lg-5 col-xl-4 position-relative d-flex flex-column justify-content-center align-items-center">
            <img *ngIf="imageUrl" [src]="imageUrl" class="author-foto-img" alt="Foto of the Author">
            <a (click)="openFotoUploadDialog()" class="author-foto-change-link" role="button">{{formGroup.get('id')?.value ? 'change foto' : 'upload foto'}}</a>
          </div>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
          <button (click)="navigateBack()" class="btn btn-secondary btn-lg">
            cancel
          </button>
          <button (click)="saveAndNavigateBack()" class="btn btn-success btn-lg px-4">
            save
          </button>
        </div>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>

// react/src/features/library/book-edit.tsx
import React, {memo, SyntheticEvent, useContext, useEffect, useState} from 'react';
import LuxonAdapter from '@date-io/luxon';
import {DatePicker, LocalizationProvider} from '@mui/lab';
import {Autocomplete, Paper, TextField} from '@mui/material';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import {EnrichedBook} from '../../mock-backend/util/book-utils';
import {useNavigate, useParams} from 'react-router-dom';
import {createOrUpdateBook, deleteBook, findBookById} from '../../mock-backend/book/book-mock-data';
import {Book} from '../../mock-backend/book/Book';
import ReactQuill, {UnprivilegedEditor} from 'react-quill';
import {DateTime} from 'luxon';
import UploadImageDialog from '../authors/upload-image-dialog';
import {GlobalMessageContext} from '../../shared/GlobalMessageContext';
import {findAllAuthors} from '../../mock-backend/author/author-mock-data';
import {Author} from '../../mock-backend/author/Author';
import ConfirmationDialog from '../../shared/confirmation-dialog';

interface BookEditState {
  loading: boolean;
  book: EnrichedBook,
  imageUrl?: string,
  showImageUploadDialog: boolean

  fotoChanged: boolean;

  showDeleteDialog: boolean,
  errors: {
    [key: string]: string | null
  }
  authors: Author[],
  currentAuthor: Author | null;
}

const BookEdit = () => {
  const globalMessageContext = useContext(GlobalMessageContext);
  const [state, setState] = useState<BookEditState>({
    loading: true,
    book: {},
    showImageUploadDialog: false,
    fotoChanged: false,
    showDeleteDialog: false,
    errors: {},
    authors: [],
    currentAuthor: null
  });
  const {id} = useParams();
  const navigate = useNavigate();

  useEffect(() => {
    console.log("useEffect");

    function loadBook() {
      if (id === "new") {
        setState((st => ({...st, loading: false})));
        return;
      }

      const bookId = Number(id);
      console.log("loadBook", bookId);

      findBookById(bookId).subscribe(
        {
          next: (book: Book) => {
            console.log("findBookById SUCCESS", book);
            const imageUrl = URL.createObjectURL(book.image!);
            setState((st => ({...st, loading: false, book, imageUrl})));
          },
          error: (error: any) => {
            console.log("findBookById ERROR", error);
            setState((st => ({...st, loading: false, book: {}, imageUrl: undefined})));
          }
        });
    }

    return loadBook();
  }, [id]);


  useEffect(() => {
    console.log("useEffect");

    function loadAuthors() {
      findAllAuthors().subscribe(
        {
          next: (authors: Author[]) => {
            console.log("findAllAuthors SUCCESS", authors);
            setState((st => ({...st, authors})));
          },
          error: (error: any) => {
            console.log("findAllAuthors ERROR", error);
          }
        });
    }

    return loadAuthors();
  }, []);


  useEffect(() => {
    console.log("effect running - trying to set currentauthor", state.book?.id, state.authors);

    if (state.book?.id && state.authors?.length > 0) {
      const currentAuthor = state.authors.find(a => a.id === state.book.authorId);
      console.log("currentAuthor found - setting it", currentAuthor);
      setState((st => ({...st, currentAuthor: currentAuthor!})));
    }
  }, [state.book, state.authors]);

  function openDeleteDialog() {
    setState({
      ...state, showDeleteDialog: true
    });
  }

  function handleInputChange(event: SyntheticEvent) {
    const target = event.target as HTMLInputElement;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const name = target.name;

    changeStateField(target.required, name as keyof Book, value);
  }

  function handleAuthorSelect(author: Author) {
    console.log("handleAuthorSelect", author);

    if (author) {
      state.errors["author"] = null;
      setState({
        ...state,
        currentAuthor: author,
        book: {...state.book, authorId: author.id, authorFullName: author.firstname + " " + author.lastname},
      });
    } else {
      state.errors["author"] = "cannot be empty";
    }
  }


  function changeStateField(required: boolean, name: keyof Book, value: any) {
    console.log("changeStateField", required, name, value);

    validateFieldAndSetErrorIfNecessary(required, name, value);

    setState({
      ...state, book: {...state.book, [name]: value},
    });
  }

  function validateFieldAndSetErrorIfNecessary(required: boolean, name: keyof Book, value: any) {
    console.log("validateFieldAndSetErrorIfNecessary", name, value, state.book[name]);

    if ((required || name === "firstPublished") && !value) {
      state.errors[name] = "Cannot be empty";
    } else if ((name === "firstPublished") && !(value as DateTime).isValid) {
      state.errors[name] = "Date is invalid";
    } else {
      state.errors[name] = null;
    }

    setState({
      ...state
    });
  }

  function onNoteBlur(range: ReactQuill.Range, value: any, editor: UnprivilegedEditor) {
    setState({...state, book: {...state.book, description: editor.getHTML()}});
  }

  function openFotoUploadDialog() {
    console.log("openfotouploadialog");
    setState({...state, showImageUploadDialog: true});
  }

  function navigateBackToBookList() {
    console.log("navigateBackToBookList");
    navigate("/book");
  }

  function saveAndNavigateToDetail() {
    console.log("saveAndNavigateToDetail", state.book);

    const requiredFields = ["title", "firstPublished", "genre", "image"];
    for (const key of requiredFields) {
      const isRequiredField = requiredFields.includes(key);
      validateFieldAndSetErrorIfNecessary(isRequiredField, key as keyof Book, state.book[key as keyof Book]);
    }

    const errorPresent = Object.values(state.errors).some(v => v);
    if (!errorPresent) {

      createOrUpdateBook(state.book).subscribe(
        {
          next: (a: Book) => {
            console.log("createOrUpdateAuthor SUCCESS", a);
            globalMessageContext.setMessage({message: "Author saved", severity: "success"});
            navigate("/library");
          },
          error: (error: any) => {
            console.log("createOrUpdateAuthor ERROR", error);
            globalMessageContext.setMessage({message: "Error saving Author", severity: "danger"});
          }
        });
    }
  }

  function handleImageAcceptedInDialog(image: Blob | undefined) {
    console.log("handleImageAcceptedInDialog", image);
    if (image) {
      setState((st) => ({
        ...st,
        errors: {...state.errors, "image": null},
        showImageUploadDialog: false,
        book: {...state.book, image: image},
        imageUrl: URL.createObjectURL(image)
      }));
    }
  }

  function deleteBookAndReturnToLibrary() {
    console.log("deleteBookAndReturnToLibrary");
    deleteBook(Number(id)).subscribe(
      {
        next: () => {
          console.log("deleteBook SUCCESS");
          globalMessageContext.setMessage({
            message: "Successfully deleted \"" + state.book.title + "\"",
            severity: "info"
          });
          navigate("/library");
        },
        error: (error: any) => {
          console.log("deleteBook ERROR", error);
          globalMessageContext.setMessage({message: "Error deleting Author", severity: "danger"});
        }
      });
  }

  return (
    <LocalizationProvider dateAdapter={LuxonAdapter}>
      <div className="comp-wrapper">
        <Paper elevation={8} className="app-col">
          <div className="title-row">
            <div className="title-row">
              <h1>
                {!state.book.id && !state.loading && "New Book"}
                {state.book.id && state.book?.title}
              </h1>
            </div>
            <button onClick={() => openDeleteDialog()} className="btn btn-danger btn-lg me-4">delete</button>
          </div>
          <LoadingIndicatorWrapper loading={state.loading}>
            <div className="pb-3">
              <div className="row mx-3 gx-0 gx-lg-5">
                <div className="col-lg-6 pt-2">
                  <h2 className="mb-2">Personal Data</h2>
                  <TextField name="title" label="Title" value={state.book.title || ''} onChange={handleInputChange}
                             required error={!!state.errors["title"]} helperText={state.errors["title"]}
                             variant="outlined" className="w-100"/>
                  <TextField name="subtitle" label="Subtitle" value={state.book.subtitle || ''} onChange={handleInputChange}
                             error={!!state.errors["subtitle"]} helperText={state.errors["subtitle"]}
                             variant="outlined" className="w-100 mt-4"/>

                  <Autocomplete
                    options={state.authors} getOptionLabel={(option) => option.firstname! + " " + option.lastname!}
                    id="combo-box-demo" className="w-100"
                    value={state.currentAuthor}
                    onChange={(event, newValue) => {
                      handleAuthorSelect(newValue!);
                    }}
                    renderInput={(params) =>
                      <TextField {...params} label="Author" className="w-100 mt-4" required
                                 error={!!state.errors["author"]} helperText={state.errors["author"]}
                      />
                    }
                  />

                  <DatePicker value={state.book.firstPublished ? state.book.firstPublished.toJSDate() : null}
                              onChange={(e) => changeStateField(true, "firstPublished", e)}
                              mask="dd.LL.yyyy" inputFormat="dd.LL.yyyy"
                              renderInput={(props) => (
                                <TextField {...props} required label="First published"
                                           error={!!state.errors["firstPublished"]} helperText={state.errors["firstPublished"]}
                                           variant="outlined" className="w-100 mt-4"/>
                              )}>
                  </DatePicker>

                  <TextField name="series" label="Series" value={state.book.series || ''} onChange={handleInputChange}
                             error={!!state.errors["series"]} helperText={state.errors["series"]}
                             variant="outlined" className="w-100 mt-4"/>
                  <TextField name="numberWithinSeries" label="Book in Series" value={state.book.numberWithinSeries || ''}
                             onChange={handleInputChange}
                             error={!!state.errors["numberWithinSeries"]} helperText={state.errors["numberWithinSeries"]}
                             variant="outlined" className="w-100 mt-4"/>

                  <TextField name="genre" label="Genre" value={state.book.genre || ''} onChange={handleInputChange}
                             error={!!state.errors["genre"]} helperText={state.errors["genre"]}
                             variant="outlined" className="w-100 mt-4"/>
                </div>

                <div className="col-lg-6 pt-2">
                  <h2 className="mt-lg-0 mb-2">Description</h2>
                  <ReactQuill value={state.book?.description || ''} onBlur={(range, value, editor) => onNoteBlur(range, value, editor)}
                              theme="snow" modules={{
                    toolbar: [
                      ['bold', 'italic', 'underline'],
                      [{'header': [1, 2, 3, 4, false]}],
                    ]
                  }}
                  />

                  <div className="d-flex align-items-center mt-4 mt-lg-3">
                    <h2 className="me-3">Cover</h2>
                    {state.errors["image"] && <div className="error-label">Please upload a foto!</div>}
                    {state.book.id && state.fotoChanged &&
                      <div className="text-danger fw-bold">You changed the cover - don't forget to save!</div>
                    }
                  </div>
                  <div
                    className="foto-wrapper col-sm-7 col-md-6 col-lg-5 col-xl-4 position-relative d-flex flex-column justify-content-center align-items-center">
                    {state.imageUrl && <img src={state?.imageUrl} className="author-foto-img" alt="Foto of the Author"/>}
                    <button type="button" onClick={openFotoUploadDialog} className="author-foto-change-link btn btn-link">
                      {state.book.id ? 'change foto' : 'upload foto'}
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <div className="row mt-3">
              <div className="col-12 px-4 px-lg-5 mb-3 d-flex align-items-center justify-content-between ">
                <button onClick={() => navigateBackToBookList()} className="btn btn-secondary btn-lg">
                  cancel
                </button>
                <button onClick={() => saveAndNavigateToDetail()} className="btn btn-success btn-lg px-4">
                  save
                </button>
              </div>
            </div>
          </LoadingIndicatorWrapper>
        </Paper>
      </div>
      <UploadImageDialog show={state.showImageUploadDialog} closeImageUploadDialog={(image) => handleImageAcceptedInDialog(image)}/>
      <ConfirmationDialog show={state.showDeleteDialog} title="Delete Book" confirmButtonType="danger"
                          message="Are you sure that you want to delete the book?" confirmButtonText="Delete" cancelButtonText="Cancel"
                          dismissDialog={() => setState({...state, showDeleteDialog: false})}
                          actionAfterConfirm={() => deleteBookAndReturnToLibrary()}
      />
    </LocalizationProvider>
  );
}

export default memo(BookEdit);
