// react/src/features/yourBooks/book-detail-dialog.tsx
import React, {memo, useState} from 'react';
import {EnrichedBook} from '../../mock-backend/util/book-utils';
import {Dialog, Link} from '@mui/material';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faTimes} from '@fortawesome/free-solid-svg-icons/faTimes';
import {useNavigate} from 'react-router-dom';
import ConfirmationDialog from '../../shared/confirmation-dialog';

interface BookDetailDialogProps {
  book: EnrichedBook,
  show: boolean,
  dismissDialog: () => void,
}

const BookDetailDialog = (props: BookDetailDialogProps) => {
  const [state, setState] = useState({showSeriesDialog: false})
  const imageUrl = URL.createObjectURL(props.book.image);
  const navigate = useNavigate();

  function dismissDialog() {
    props.dismissDialog();
  }

  function navigateToBookEditPage() {
    navigate("/library/edit/" + props.book.id);
  }

  function openSeriesDialog() {
    setState({showSeriesDialog: true});
  }

  function navigateToAuthorDetail() {
    navigate("/library/edit/" + props.book.authorId);
  }

  function dismissSeriesDialog() {
    setState({showSeriesDialog: false});
  }

  return (
    <Dialog onClose={() => dismissDialog()} open={props.show}>
      <div className="p-4">
        <div className="d-flex align-items-center justify-content-between">
          <div className="d-flex align-items-center">
            <h1>{props.book.title}</h1>
            <button onClick={() => navigateToBookEditPage()} className="btn btn-warning btn-lg ms-2 ms-lg-4 me-5">edit</button>
          </div>
          <FontAwesomeIcon onClick={() => dismissDialog()} icon={faTimes} size={'2x'}/>
        </div>
        <div className="d-flex flex-column flex-md-row">
          <div>
            <div className="subtitle">{props.book.subtitle}</div>
            {props.book.series && <div className="series fs-5">Book {props.book.numberWithinSeries} of
              <Link className="ms-1 series fs-5" onClick={() => openSeriesDialog()}>{props.book.series}</Link>
            </div>
            }
            <div className="mt-2 by-label">by <Link onClick={() => navigateToAuthorDetail()}
                                                    className="by-label">{props.book.authorFullName}</Link></div>
            <div className="mt-2 first-published">first published {props.book.firstPublished?.toFormat("dd.LL.yyyy")}</div>

            <div className="description">{props.book.description}</div>
          </div>
          <div className="book-foto-wrapper ms-0 ms-md-4">
            <img src={imageUrl} alt="Foto of the Author" className="book-image"/>
          </div>
        </div>
      </div>
      <ConfirmationDialog show={state.showSeriesDialog} title={props.book.series!} confirmButtonType="danger"
                          dismissDialog={() => dismissSeriesDialog()} cancelButtonText="go back"
                          message="Got me :)<br /><br />In a <u>real application</u> this could display the series with all it's books.<br/>This feature is not part of the demo though and therefore <strong>not implemented</strong> - sorry!"
      />
    </Dialog>
  )
}

export default memo(BookDetailDialog);

// vue/src/components/library/BookDetailDialog.vue
<template>
  <q-dialog :model-value="props.show" @hide="closeSeriesDialog">
    <q-card class="my-card p-4" style="min-width: 280px">
      <div class="d-flex align-items-start align-items-lg-center justify-content-start flex-column flex-md-row">
        <h1>{{ book?.title }}</h1>
        <button @click="navigateToBookEditPage()" class="btn btn-warning btn-lg ms-2 ms-lg-4 me-5">edit</button>
      </div>
      <div class="d-flex flex-column flex-md-row">
        <div>
          <div class="subtitle">{{ book?.subtitle }}</div>
          <div v-if="book?.series" class="series">Book {{ book?.numberWithinSeries }} of
            <a @click="openSeriesDialog" role="button" class="series-link">{{ book?.series }}</a>
            <ConfirmationDialog :show=showSeriesDialog :title="book.series" confirmButtonType="danger" :hide-confirm-button="true"
                                @closeDialog="closeSeriesDialog" cancelButtonText="go back"
                                message="Got me :)<br /><br />In a <u>real application</u> this could display the series with all it's books.<br/>This feature is not part of the demo though and therefore <strong>not implemented</strong> - sorry!"
            />
          </div>
          <div class="mt-2 author">by
            <router-link to="/author/{{book?.authorId}}">{{ book?.authorFullName }}</router-link>
            <div class="mt-2 first-published">first published {{ book?.firstPublished?.toFormat("dd.LL.yyyy") }}</div>

            <div class="description" v-html="book?.description"></div>
          </div>
        </div>
        <div class="book-foto-wrapper ms-0 ms-md-4">
          <img :src="imageUrl" class="book-image" alt="Foto of the Author">
        </div>
      </div>
    </q-card>
  </q-dialog>
</template>

<script setup lang="ts">
import ConfirmationDialog from '@/components/shared/ConfirmationDialog.vue';
import type {EnrichedBook} from '../../../../react/src/mock-backend/util/book-utils';
import type {Ref} from 'vue';
import {onMounted, ref} from 'vue';
import {createImageUrlFromBlob} from '@/util/ImageService';

const showSeriesDialog: Ref<boolean> = ref(false);

const props = defineProps<{
  show: boolean,
  book: EnrichedBook
}>();
const emit = defineEmits(['closeDialog']);
const imageUrl: Ref<string | undefined> = ref(undefined);

onMounted(() => {
  console.log(`onMounted BookCard`, props.book);
  imageUrl.value = createImageUrlFromBlob(props.book.image);
})


function navigateToBookEditPage() {
  emit("closeDialog");
}

function openSeriesDialog() {
  showSeriesDialog.value = true;
}

function closeSeriesDialog() {
  console.log("handle close series dialog");
  showSeriesDialog.value = false;
}
</script>

<style scoped lang="scss">
.subtitle {
  font-size: 1.3rem;
}

.first-published {
  color: #656565;
  font-size: 0.8rem
}

.description {
  font-size: 0.7rem;

  @media (min-width: 768px) {
    font-size: 1rem;
  }
}

.book-image {
  width: 186px;
}

@media (min-width: 600px) {
  .q-dialog__inner--minimized > div {
    max-width: 900px;
  }
}
</style>
