// vue/src/components/library/IsInLibraryMarker.vue
<template>
  <q-btn-dropdown
    split
    to="/start/pick-quasar-flavour"
    color="grey-7"
  >
    <template v-slot:label>
      <div v-if="status ==='default'" @click="changeStatus('want to read')" class="button-label">
        want to read
      </div>

      <div v-if="status !=='default'" type="button" class="already-chosen-button d-flex align-items-center justify-content-center">

        <span class="ms-2">{{ status }}</span>
        <font-awesome-icon v-if="status === 'want to read'" icon="bookmark" class="mx-2 icon-want-to-read"/>
        <font-awesome-icon v-if="status === 'currently reading'" icon="bookReader" class="mx-2 icon-currently-reading"/>
        <font-awesome-icon v-if="status === 'read'" icon="check" class="mx-2 icon-read"/>
      </div>
    </template>
    <ul class="list-group">
      <li v-if="status !== 'want to read'"><a class="list-group-item" @click="changeStatus('want to read')">want to read</a></li>
      <li v-if="status !== 'read'"><a class="list-group-item" @click="changeStatus('read')">read</a></li>
      <li v-if="status !== 'currently reading'"><a class="list-group-item" @click="changeStatus('currently reading')">currently reading</a>
      </li>
      <li v-if="status !== 'default'"><a class="list-group-item" @click="changeStatus('default')">not interested</a></li>
    </ul>
  </q-btn-dropdown>
</template>

<script setup lang="ts">
import type {UserBookAssignmentStatus} from '../../../../react/src/mock-backend/user/user-book-assignment-status';

const props = defineProps<{
  status: UserBookAssignmentStatus
}>()
const emit = defineEmits(['statusChange'])

function changeStatus(status: UserBookAssignmentStatus) {
  emit('statusChange', status);
}
</script>

<style scoped>
li {
  cursor: pointer;
}

.button-label {
  font-family: Verdana, serif;
  font-weight: 700;
}

</style>

// angular/src/app/shared/is-in-library-marker/is-in-library-marker.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {UserBookAssignmentStatus} from '@mock-backend/../../../../../react/src/mock-backend/user/user-book-assignment-status';
import {faBookmark, faBookReader, faCheck} from '@fortawesome/free-solid-svg-icons';


@Component({
  selector: 'app-is-in-library-marker',
  templateUrl: './is-in-library-marker.component.html',
  styleUrls: ['./is-in-library-marker.component.scss']
})
export class IsInLibraryMarkerComponent implements OnInit {
  isMenuCollapsed = false;

  @Input() status?: UserBookAssignmentStatus;

  @Output() statusChange = new EventEmitter<UserBookAssignmentStatus>();

  iconBookmark = faBookmark;
  iconBookReader = faBookReader;
  iconCheck = faCheck;

  ngOnInit(): void {
    if (!this.status) {
      throw new Error("IsInLibraryMarkerComponent rewuires currentStatus to be set");
    }
  }

  changeStatus(status: UserBookAssignmentStatus) {
    this.isMenuCollapsed = false;
    this.statusChange.next(status)
  }
}

<div class="btn-group mb-3">
  <button *ngIf="status ==='default'" (click)="changeStatus('want to read')" type="button" class="btn btn-secondary btn-sm btn-main">want to read</button>

  <div *ngIf="status !=='default'" type="button" class="already-chosen-button d-flex align-items-center justify-content-center">
    <span class="ms-2">{{status}}</span>
    <fa-icon *ngIf="status === 'want to read'" [icon]="iconBookmark" class="mx-2 icon-want-to-read"></fa-icon>
    <fa-icon *ngIf="status === 'currently reading'" [icon]="iconBookReader" class="mx-2 icon-currently-reading"></fa-icon>
    <fa-icon *ngIf="status === 'read'" [icon]="iconCheck" class="mx-2 icon-read"></fa-icon>
  </div>

  <button (click)="isMenuCollapsed=!isMenuCollapsed" type="button" class="btn btn-secondary btn-sm dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="visually-hidden">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu cursor-pointer" [class.d-block]="isMenuCollapsed">
    <li *ngIf="status !== 'want to read'"><a class="dropdown-item" (click)="changeStatus('want to read')">want to read</a></li>
    <li *ngIf="status !== 'read'"><a class="dropdown-item" (click)="changeStatus('read')">read</a></li>
    <li *ngIf="status !== 'currently reading'"><a class="dropdown-item" (click)="changeStatus('currently reading')">currently leading</a></li>
    <li *ngIf="status !== 'default'"><a class="dropdown-item" (click)="changeStatus('default')">not interested</a></li>
  </ul>
</div>
