// vue/src/App.vue
<script setup lang="ts">
import {RouterView} from 'vue-router'
import Header from '@/components/HeaderMenu.vue';</script>

<template>
  <Header/>
  <div class="container-fluid" style="margin-top:55px;">
    <div class="row">
      <div>
        <RouterView/>
      </div>
    </div>
  </div>
</template>

<style>

</style>

// angular/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-bookstore';
}

<app-header></app-header>
<div class="container-fluid" style="margin-top:55px;">
  <div class="row">
    <router-outlet></router-outlet>
  </div>
</div>
<app-global-message></app-global-message>
