// angular/src/app/shared/loading-indicator-overlay-wrapper/loading-indicator-overlay-wrapper.component.ts
import {Component, Input} from '@angular/core';
import {SizeProp} from '@fortawesome/fontawesome-svg-core';

@Component({
  selector: 'app-loading-indicator-overlay-wrapper',
  templateUrl: './loading-indicator-overlay-wrapper.component.html',
  styleUrls: ['./loading-indicator-overlay-wrapper.component.scss'],
})
export class LoadingIndicatorOverlayWrapperComponent {
  @Input() showOverlay = false;
  @Input() spinnerSize: SizeProp = "3x";

}

<div class="rounded position-relative">
  <div class="overlay-base icon-wrapper" [class.overlay-backdrop]="showOverlay">

    <div class="icon-wrapper d-flex align-items-center justify-content-center">
      <fa-icon *ngIf="showOverlay" icon="spinner" [size]="spinnerSize" [classes]="['fa-spin']"></fa-icon>
    </div>

    <ng-content></ng-content>

  </div>
</div>

// vue/src/components/shared/LoadingIndicatorOverlayWrapper.vue
<template>
  <div class="rounded">
    <div class="overlay-base" :class="{ 'overlay-backdrop': showOverlay }">
      <div class="icon-wrapper d-flex align-items-center justify-content-center">
        <font-awesome-icon v-if="showOverlay" icon="spinner" :size="spinnerSize" class="fa-spin"/>
      </div>
      <slot></slot>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  showOverlay: boolean,
  spinnerSize: string //TODO find out how to use default setting
  // spinnerSize: {
  //   type: string,
  //   default: '3x'
  // },
}>()
</script>

<style scoped>
.overlay-base {
  background: transparent;
  transition: background 0.4s linear;
}

.overlay-base.overlay-backdrop {
  opacity: 1;
  background: rgba(0, 0, 0, 0.3);
  z-index: 1000;
  pointer-events: none;
}

.icon-wrapper {
  position: absolute;
  top: 250px;
  left: 0;
  right: 0;
  pointer-events: none;
}

</style>
