// react/src/features/library/library.tsx
import React, {ChangeEvent, useContext, useEffect, useRef, useState} from 'react';
import {Paper} from '@mui/material';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import {faFilter} from '@fortawesome/free-solid-svg-icons';
import LoadingIndicatorWrapper from '../../shared/loading-indicator-wrapper';
import BookCard from '../yourBooks/book-card';
import ApplicationContext from '../../shared/ApplicationContext';
import {enrichBookWithUserAssignments, EnrichedBook} from '../../mock-backend/util/book-utils';
import {Book} from '../../mock-backend/book/Book';
import {findAllBooks} from '../../mock-backend/book/book-mock-data';
import {findUserBookAssignmentsForUser, updateStatus} from '../../mock-backend/user/user-book-assignment-mockservice';
import {useNavigate} from 'react-router-dom';
import {UserBookAssignmentStatus} from '../../mock-backend/user/user-book-assignment-status';

interface LibraryState {
  loading: boolean,
  books: EnrichedBook[],
  filteredBooks: EnrichedBook[],
  searchTerm: string
  selectAllFilter: "exclude your books" | "show all books";
}

const Library = () => {
  const applicationContextRef = useRef(useContext(ApplicationContext));
  const [state, setState] = useState<LibraryState>({
    loading: true,
    books: [],
    filteredBooks: [],
    searchTerm: "",
    selectAllFilter: "exclude your books"
  })
  const navigate = useNavigate();

  const filterRef = React.useRef<HTMLInputElement>(null);

  React.useEffect(() => {
    filterRef.current?.focus();
  }, []);

  useEffect(() => {
    console.log("useEffect running - should never rerun, since the dependencies-array is empty - loading books");
    findAllBooks().subscribe(
      {
        next: (results: Book[]) => {
          console.log("findBooksForUser SUCCESS", results);
          const books = results.map(b => enrichBookWithUserAssignments(b, applicationContextRef.current.user!));
          const filteredBooks = filter(books, "", "exclude your books");
          setState(st => ({
            ...st,
            loading: false,
            books,
            filteredBooks
          }));
        },
        error: (error: any) => {
          console.log("findBooksForUser ERROR", error);
          setState(st => ({...st, loading: false}));
        }
      });
  }, []); // runs exactly once, because the deps array is empty, therefor it will never be re-evaluated#

  function handleFilterKeyup(event: ChangeEvent<HTMLInputElement>) {
    const searchTerm = (event.target as HTMLInputElement).value.toLowerCase();
    console.log("handleFilterKeyup", searchTerm);
    const filteredBooks = filter(state.books, searchTerm, state.selectAllFilter);
    setState({...state, searchTerm, filteredBooks});
  }

  function handleSelectAllChange(e: any) {
    const selectedOption = e.target.value;
    console.log("handleFilterKeyup", selectedOption);
    const filteredBooks = filter(state.books, state.searchTerm, e.target.value);
    setState({...state, selectAllFilter: selectedOption, filteredBooks});
  }


  function filter(books: EnrichedBook[], searchTerm: string, showAllSelectFilter: "exclude your books" | "show all books"): EnrichedBook[] {
    let allBooks = books;
    console.log("filter", searchTerm, showAllSelectFilter);
    if (showAllSelectFilter === 'exclude your books') {
      allBooks = allBooks.filter((book: EnrichedBook) => !(findUserBookAssignmentsForUser(applicationContextRef.current.user!).map(b => b.bookId).includes(book.id!)))
    }

    return allBooks.filter((b: EnrichedBook) => b.title?.toLocaleLowerCase().includes(searchTerm));
  }

  function navigateToNewBook() {
    navigate("/library/edit/new");
  }

  function handleAssignmentStatusChange(book: EnrichedBook, stat: UserBookAssignmentStatus) {
    console.log("LibraryComponent: statusChanged received", book, stat);
    updateStatus(applicationContextRef.current.user!, book.id!, stat);

  }

  return (
    <div className="comp-wrapper">
      <Paper elevation={8} className="app-col">
        <div className="title-row">
          <div className="d-flex align-items-center justify-content-between w-100">
            <div className="d-flex align-items-center justify-content-start flex-wrap">
              <h1 className="me-2 me-lg-5">Library</h1>
              <div className="input-group me-2 me-lg-5 my-2 my-lg-0" style={{width: 260}}>
                <input value={state.searchTerm} onChange={(e) => handleFilterKeyup(e)} className="form-control"
                       ref={filterRef} placeholder="filter by name" aria-label="Filter"/>
                <span className="input-group-text"><FontAwesomeIcon icon={faFilter}/></span>
              </div>
              <div className="input-group" style={{width: 260}}>
                <select value={state.selectAllFilter} onChange={(e) => handleSelectAllChange(e)} className="form-select" aria-label="exclude your
              books or show all">
                  <option>exclude your books</option>
                  <option>show all books</option>
                </select>
              </div>
            </div>
            <button onClick={() => navigateToNewBook()} className="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">
              add book
            </button>
          </div>
        </div>
        <div>
          <LoadingIndicatorWrapper loading={state.loading}>
            <div className="row mx-1 mx-lg-2 justify-content-around pb-4" style={{minHeight: 400}}>
              {state.filteredBooks.map((b) => (
                <div key={b.id} className="col-auto g-4 book-card-wrap">
                  <BookCard key={b.id} book={b} changeStatus={handleAssignmentStatusChange}/>
                </div>
              ))}
            </div>
          </LoadingIndicatorWrapper>
        </div>
      </Paper>
    </div>
  )
    ;
};

export default Library;

// angular/src/app/features/library/library/library.component.ts
import {Component, OnInit} from '@angular/core';
import {findAllBooks} from'@mock-backend/book/book-mock-data';
import {Book} from'@mock-backend/book/Book';
import {GlobalMessageService} from '@core/global-message.service';
import {BehaviorSubject, combineLatest, map, Observable} from 'rxjs';
import {BookDetailDialogWrapperComponent} from '@shared/book-detail-dialog-wrapper/book-detail-dialog-wrapper.component';
import {MatDialog} from '@angular/material/dialog';
import {Router} from '@angular/router';
import {UserService} from '@core/user.service';
import {UserBookAssignmentStatus} from'@mock-backend/user/user-book-assignment-status';
import {findUserBookAssignmentsForUser, updateStatus} from'@mock-backend/user/user-book-assignment-mockservice';
import {enrichBookWithUserAssignments, EnrichedBook} from '@mock-backend/util/book-utils';

type ShowAllSelectTypes = "HIDE_YOUR_BOOKS" | "SHOW_ALL";

@Component({
  selector: 'app-library',
  templateUrl: './library.component.html',
  styleUrls: ['./library.component.scss']
})
export class LibraryComponent implements OnInit {

  filterByName$ = new BehaviorSubject("");
  showAllSelectFilter$ = new BehaviorSubject<ShowAllSelectTypes>("HIDE_YOUR_BOOKS");
  filteredBooks$?: Observable<EnrichedBook[]>

  constructor(private globalMessageService: GlobalMessageService, private matDialog: MatDialog,
              private router: Router, private userService: UserService) {
  }


  ngOnInit(): void {
    console.log("LibraryComponent ngOnInit");

    this.filteredBooks$ = combineLatest([this.filterByName$, this.showAllSelectFilter$, findAllBooks()]).pipe(
      map((combination: any) => {
        const filterTerm = combination[0].toLowerCase();
        const showAllSelectFilter = combination[1];
        let allBooks = combination[2].map((b: Book) => enrichBookWithUserAssignments(b, this.userService.authentication$.getValue()));
        console.log("filtering by \"" + filterTerm + "\"", showAllSelectFilter, allBooks.length);
        if (showAllSelectFilter === 'HIDE_YOUR_BOOKS') {
          allBooks = allBooks.filter((book: EnrichedBook) => !(findUserBookAssignmentsForUser(this.userService.authentication$.getValue()).map(b => b.bookId).includes(book.id)))
        }

        return allBooks.filter((b: EnrichedBook) => b.title.toLocaleLowerCase().includes(filterTerm));
      }),
    );
  }

  filter(searchTerm: string) {
    this.filterByName$.next(searchTerm);
  }

  navigateToNewBook() {
    this.router.navigate(["/library/edit/new"]);
  }

  openBookDetail(book: Book) {
    this.matDialog.open(BookDetailDialogWrapperComponent, {
      data: {book},
      maxHeight: "70vh",
      maxWidth: "900px"
    }).afterClosed().subscribe((result) => {
      if (result?.openEditPage) {
        this.router.navigate(["/library/edit", book.id]);
      }
    });
  }

  handleStatusChanged(event: { book: Book, status: UserBookAssignmentStatus }) {
    console.log("LibraryComponent: statusChanged received", event);
    updateStatus(this.userService.authentication$.getValue(), event.book.id, event.status);
  }

  handleSelectAllChange(value: string) {
    const selectAllChange = value as ShowAllSelectTypes;
    this.showAllSelectFilter$.next(selectAllChange);
  }
}

<div class="app-col mat-elevation-z8">
  <div class="p-2 ms-lg-3 title-row">
    <div class="d-flex align-items-center justify-content-between flex-wrap">
      <div class="d-flex flex-wrap align-items-center">
        <h1 class="me-2 me-lg-5">Library</h1>
        <div class="input-group me-2 me-lg-5 my-2 my-lg-0" style="width: 260px">
          <input #searchTerm (keyup)="filter(searchTerm.value)" autofocus class="form-control" placeholder="type to filter by name" aria-label="Filter">
          <span class="input-group-text"><mat-icon>filter_alt</mat-icon></span>
        </div>
        <div class="input-group" style="width: 260px">
          <select #showAllSelect (change)="handleSelectAllChange(showAllSelect.value)" class="form-select" aria-label="exclude your books or show all">
            <option selected [value]="'HIDE_YOUR_BOOKS'">exclude your books</option>
            <option [value]="'SHOW_ALL'">show all books</option>
          </select>
        </div>
      </div>
      <button (click)="navigateToNewBook()" class="btn btn-success btn-lg me-2 me-lg-4 mt-2 mt-lg-0">
        add book
      </button>
    </div>
  </div>
  <div *ngIf="{filteredBooks: (filteredBooks$ | async)} as obs" style="border-top: 2px solid gray;">
    <app-loading-indicator-overlay-wrapper [showOverlay]="!obs.filteredBooks" spinnerSize="6x">

      <div class="row mx-1 mx-lg-2 justify-content-around pb-4" style="min-height: 300px;">
        <div *ngFor="let book of obs.filteredBooks" class="col-auto g-4 book-card-wrap">
          <app-book-card [book]="book" (openDetail)="openBookDetail($event)" (statusChanged)="handleStatusChanged($event)"></app-book-card>
        </div>
      </div>
    </app-loading-indicator-overlay-wrapper>
  </div>
</div>
