// react/src/features/authors/author-table.tsx
import React, {memo} from 'react';
import {EnrichedAuthor} from '@local/mock-backend/author/EnrichedAuthor';
import {Box, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TableSortLabel} from '@mui/material';
import {faCheck} from '@fortawesome/free-solid-svg-icons';
import {FontAwesomeIcon} from '@fortawesome/react-fontawesome';
import GenderDisplay from '../../shared/GenderDisplay';
import {useWindowSize} from '../../util/window-resize.hook';

interface AuthorTableProps {
  authors: EnrichedAuthor[];
  authorSelected: (author: EnrichedAuthor) => void;
}

const AuthorTable = (props: AuthorTableProps) => {
  const [order, setOrder] = React.useState<"asc" | "desc">('asc');
  const [orderBy, setOrderBy] = React.useState('lastname');
  const [width] = useWindowSize();

  console.log("AuthorTable", props);

  const createSortHandler = (property: string) => (event: any) => {
    handleRequestSort(event, property);
  };

  const handleRequestSort = (event: any, property: string) => {
    const isAsc = orderBy === property && order === 'asc';
    setOrder(isAsc ? 'desc' : 'asc');
    setOrderBy(property);
  };

  console.log("AuthorTable");
  const columns = [
    {field: 'firstname', headerName: 'FIRSTNAME', alwaysShow: true},
    {field: 'lastname', headerName: 'LASTNAME', alwaysShow: true},
    {field: 'gender', headerName: 'GENDER', alwaysShow: false},
    {field: 'penName', headerName: 'PEN NAME', alwaysShow: false},
    {field: 'birthdate', headerName: 'BIRTHDATE', alwaysShow: false},
    {field: 'age', headerName: 'AGE', alwaysShow: false},
    {field: 'dateOfDeath', headerName: 'DATE OF DEATH', alwaysShow: false}
  ];

  //TODO show spinner
  function descendingComparator(a: any, b: any, field: string) {
    if (!b[field] || b[field] < a[field]) {
      return -1;
    }
    if (!a[field] || b[field] > a[field]) {
      return 1;
    }
    return 0;
  }

  function getComparator(direction: string, field: string) {
    return direction === 'desc'
        ? (a: any, b: any) => descendingComparator(a, b, field)
        : (a: any, b: any) => -descendingComparator(a, b, field);
  }

  function handleRowSelected(author: EnrichedAuthor) {
    props.authorSelected(author);
  }

  return (
      <>
        <TableContainer component={Paper}>
          <Table size="small" aria-label="simple table">
            <TableHead>
              <TableRow>
                {columns.map(h =>
                    <TableCell key={h.field} sx={{display: ((!h.alwaysShow && width <= 800) ? "none" : "table-cell")}}>
                      <TableSortLabel active={orderBy === h.field} direction={order}
                                      onClick={createSortHandler(h.field)}>
                        <Box component="span" sx={{display: "box"}}>
                          {h.headerName}
                        </Box>
                      </TableSortLabel>
                    </TableCell>
                )}
              </TableRow>
            </TableHead>
            <TableBody>
              {props.authors.slice().sort(getComparator(order, orderBy)).map((a: EnrichedAuthor) => (
                  <TableRow
                      onClick={() => handleRowSelected(a)}
                      key={a.id}
                      sx={{'&:last-child td, &:last-child th': {border: 0}}}
                      className="selectable-table-row"
                  >
                    <TableCell component="th" scope="row">{a.firstname}</TableCell>
                    <TableCell component="th" scope="row">{a.lastname}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}><GenderDisplay
                        gender={a.gender}/></TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.penName ?
                        <FontAwesomeIcon icon={faCheck} size={'lg'}/> : ""}</TableCell>
                    <TableCell component="th" scope="row"
                               sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.birthdate?.toFormat("dd.LL.yyyy")} in {a.placeOfBirth}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>{a.age}</TableCell>
                    <TableCell component="th" scope="row" sx={{display: ((width <= 800) ? "none" : "table-cell")}}>
                      {a.dateOfDeath ? (a.dateOfDeath?.toFormat("dd.LL.yyyy") + " in " + a.placeOfDeath) : ""}
                    </TableCell>
                  </TableRow>
              ))}
            </TableBody>
          </Table>
        </TableContainer>
      </>
  );
};

export default memo(AuthorTable);

// angular/src/app/features/authors/author-table/author-table.component.ts
import {ChangeDetectionStrategy, Component, EventEmitter, HostListener, Input, OnInit, Output} from '@angular/core';
import {Sort} from '@angular/material/sort';
import {EnrichedAuthor} from '@mock-backend/author/EnrichedAuthor';
import {booleanCompare, compare, dateCompare} from '@shared/util/sort-utility';

@Component({
  selector: 'app-author-table',
  templateUrl: './author-table.component.html',
  styleUrls: ['./author-table.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AuthorTableComponent implements OnInit {

  @HostListener('window:resize', ['$event'])
  getScreenSize() {
    if (window.innerWidth >= 992) {
      this.showAllDetails = true;
      this.displayedColumns = ['firstname', 'lastname', 'gender', 'penName', 'birthdateWithPlace', 'age', 'dateOfDeath'];
    } else if (window.innerWidth >= 576) {
      this.showAllDetails = true;
      this.displayedColumns = ['firstname', 'lastname', 'birthdate', 'gender'];
    } else {
      this.showAllDetails = false;
      this.displayedColumns = ['firstname', 'lastname'];
    }
  }

  _authors: EnrichedAuthor[] = [];
  sortedAuthors: EnrichedAuthor[] = [];
  showAllDetails = false;
  private sort: Sort;

  displayedColumns: string[] = [];

  @Output()
  selectAuthor = new EventEmitter<EnrichedAuthor>();

  @Input()
  set authors(authors: EnrichedAuthor[]) {
    this._authors = authors;
    this.sortData(this.sort);
  }

  constructor() {
    this.sort = {active: "lastname", direction: "asc"}; // default sort
  }

  ngOnInit(): void {
    this.getScreenSize();
  }

  onAuthorSelect(author: EnrichedAuthor) {
    this.selectAuthor.next(author);
  }

  sortData(sort: Sort) {
    this.sort = sort;
    const data = this._authors.slice();
    if (!sort.active || sort.direction === '') {
      this.sortedAuthors = data;
      return;
    }

    this.sortedAuthors = data.sort((a, b) => {
      const isAsc = sort.direction === 'asc';
      switch (sort.active) {
        case 'age':
          return compare(a.age!, b.age!, isAsc);
        case 'firstname':
          return compare(a.firstname!, b.firstname!, isAsc);
        case 'lastname':
          return compare(a.lastname!, b.lastname!, isAsc);
        case 'penName':
          return booleanCompare(a.penName!, b.penName!, isAsc);
        case 'birthdate':
        case 'birthdateWithPlace':
          return dateCompare(a.birthdate, b.birthdate, isAsc);
        case 'gender':
          return compare(a.gender!, b.gender!, isAsc);
        case 'dateOfDeath':
          return dateCompare(a.dateOfDeath, b.dateOfDeath, isAsc);
        default:
          return 0;
      }
    });
  }
}

<table *ngIf="sortedAuthors" [dataSource]="sortedAuthors" mat-table class="selectable-table w-100" aria-label="Author Table"
       matSort (matSortChange)="sortData($event)" matSortActive="lastname" matSortDirection="asc" [matSortDisableClear]="true">
  <ng-container matColumnDef="firstname">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col">FIRSTNAME</th>
    <td mat-cell *matCellDef="let element"> {{element.firstname}} </td>
  </ng-container>
  <ng-container matColumnDef="lastname">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col">LASTNAME</th>
    <td mat-cell *matCellDef="let element"> {{element.lastname}} </td>
  </ng-container>
  <ng-container matColumnDef="penName">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col">PEN NAME</th>
    <td mat-cell *matCellDef="let element">
      <fa-icon *ngIf="element.penName" icon="check" size="lg"></fa-icon>
    </td>
  </ng-container>
  <ng-container matColumnDef="gender">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col"> GENDER</th>
    <td mat-cell *matCellDef="let element">
      <app-gender-icon [gender]="element.gender" [showLabel]="showAllDetails"></app-gender-icon>
    </td>
  </ng-container>
  <ng-container matColumnDef="age">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col"> AGE</th>
    <td mat-cell *matCellDef="let element"> {{element.age}} </td>
  </ng-container>
  <ng-container matColumnDef="birthdate">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col">BIRTHDATE</th>
    <td mat-cell *matCellDef="let element"> {{element.birthdate | date }} </td>
  </ng-container>
  <ng-container matColumnDef="birthdateWithPlace">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col">BIRTHDATE</th>
    <td mat-cell *matCellDef="let element"> {{element.birthdate | date }}, {{element.placeOfBirth}} </td>
  </ng-container>
  <ng-container matColumnDef="dateOfDeath">
    <th mat-header-cell *matHeaderCellDef mat-sort-header="" scope="col"> DATE OF DEATH</th>
    <td mat-cell *matCellDef="let element">
      {{element.dateOfDeath | date }}<span *ngIf="element.dateOfDeath">, {{element.placeOfDeath}}</span>
    </td>
  </ng-container>

  <tr mat-header-row *matHeaderRowDef="displayedColumns" class="table-header"></tr>
  <tr mat-row *matRowDef="let row; columns: displayedColumns;" (click)="onAuthorSelect(row)" class="table-row"></tr>
</table>
